### ISSUE TITLE
Share is not included in graph_values.yml if flexible: true

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#105]
Some edges have the property ``flexible: true`` in the ETLocal front-end to ensure that the sum of a share group set by the user equals 100%. However, at the moment ETLocal does not include the edges with ``flexible: true`` in the graph_values.yml output. This results in a Refinery error because the missing share is set equal to the NL default, resulting in a share group with a sum not equal to 100%

![etlocal httplocalhost3000 2018-05-09 14-44-29](https://user-images.githubusercontent.com/32056448/39815209-90131b94-5397-11e8-8455-aaf58fae30cb.png)

**Comment by ChaelKruip** [comment]
Nice catch!
