### ISSUE TITLE
Shares sometimes don't sum up to 100%

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#109]
When changing shares in Buildings -> Advanced -> Electricity distribution (by randomly clicking the slider bars), the result does not always sum up to 1. The graph_values.yml contains shares with a lot of decimals:
![sadsad](https://user-images.githubusercontent.com/32056448/39824073-c5131af8-53ae-11e8-8b35-5c5765dbc74f.png)

Sometimes it does succeed, but again ETLocal shows a lot of decimals:
![monosnap 2018-05-09 17-22-49](https://user-images.githubusercontent.com/32056448/39824295-49160f68-53af-11e8-919a-49da8d9fe41a.png)

I think it is sufficient if the shares directly set by the user in the front-end are limited to 2 decimal places.

NOTE: not all shares in the graph_values.yml are directly set by the user, some are the result of some calculations and hence should not be limited to 2 decimal places

**Comment by grdw** [comment]
Shouldn't [cooling](https://github.com/quintel/etsource/blob/master/edges/buildings/buildings_final_demand_electricity-buildings_final_demand_for_cooling_electricity%40electricity.ad) be a 'flexible' share in ETSource? Much like it is now in ETLocal. 

When I fill in (for example): 

<img width="636" alt="screen shot 2018-05-11 at 09 12 50" src="https://user-images.githubusercontent.com/2676542/39911393-80a1bd54-54fb-11e8-9294-3c270e66e0aa.png">

and try to validate it, these become my `graph_values.yml`:

<img width="1367" alt="screen shot 2018-05-11 at 09 14 24" src="https://user-images.githubusercontent.com/2676542/39911460-c2cbdcaa-54fb-11e8-9d51-57bfb17b2e06.png">

I assumed the `cooling` slider to fix the 'rest' but I think what's going on is the same issue that's happening at: #105

**Comment by grdw** [comment]
I tried something different: 

<img width="960" alt="screen shot 2018-05-11 at 09 31 08" src="https://user-images.githubusercontent.com/2676542/39912162-16ed29d6-54fe-11e8-9f94-184d186ecaa8.png">

If I give all the energy to lighting (I get this error) 🤔

**Comment by grdw** [comment]
Changing the buildings cooling edge to:

```diff
diff --git a/edges/buildings/buildings_final_demand_electricity-buildings_final_demand_for_cooling_electricity@electricity.ad b/edges/buildings/buildings_final_demand_electricity-buildings_final_demand_for_cooling_electricity@electricity.ad
index 859ef8a21..9147cac6e 100644
--- a/edges/buildings/buildings_final_demand_electricity-buildings_final_demand_for_cooling_electricity@electricity.ad
+++ b/edges/buildings/buildings_final_demand_electricity-buildings_final_demand_for_cooling_electricity@electricity.ad
@@ -1,6 +1,3 @@
-- type = share
+- type = flexible
 - reversed = false
 - groups = []
-- graph_methods = [parent_share]
-
-~ parent_share = SHARE(buildings_final_demand_electricity_parent_share, buildings_final_demand_for_cooling_electricity)

```

Doesn't do much, instead it doubles the demand to the `buildings_final_demand_electricity` whenever one of the application shares is set to 100% (except cooling).

**Comment by grdw** [comment]
Closing this, as it's fixed by rounding the defaults to 2 digits.
