### ISSUE TITLE
Add option to switch language

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#111]
Maybe we can add a Dutch and British flag to switch between languages, for example here:

![monosnap 2018-05-11 16-25-27 1](https://user-images.githubusercontent.com/32056448/39929595-bc2d6f8e-5538-11e8-8879-da09857ddb32.png)

**Comment by grdw** [comment]
It can also be an option to let the user choose a language the moment they sign up for ETLocal. A user can than edit their language preferences in some sort of edit screen.

**Comment by michieldenhaan** [comment]
That's an interesting idea. However, I think that quite a few of our future users will use ETLocal just to inspect the data behind a dataset, check our sources/assumptions etc. and won't be making any edits to the data themselves. So they probably won't have the need to sign up at all

**Comment by grdw** [comment]
Currently it's not yet possible for a non-signed in person to enter ETLocal.

**Comment by michieldenhaan** [comment]
Can this be disabled?

**Comment by grdw** [comment]
Yes, this will take a day max.

**Comment by grdw** [comment]
I made it possible to view a dataset without having to sign in: https://github.com/quintel/etlocal/commit/c76d6ad4498761d03ac2f1ac65ee4a4db46e1ad7
