### ISSUE TITLE
Reduce spacing slider group

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#115]
I think the spacing between sliders in a slider group can be reduced greatly to make the interface look more compact
![monosnap 2018-05-14 14-40-09](https://user-images.githubusercontent.com/32056448/39998015-02b0f02c-5785-11e8-84a3-a8cd91a29ff7.png)

**Comment by grdw** [comment]
![screen shot 2018-05-22 at 11 48 20](https://user-images.githubusercontent.com/2676542/40355184-0c422714-5db6-11e8-8546-26e1bfa9dd2f.png)

Like this?

**Comment by grdw** [comment]
In retrospect; at first I liked it - but than I remembered why I did this:

![screen shot 2018-05-22 at 11 51 06](https://user-images.githubusercontent.com/2676542/40355359-72247f46-5db6-11e8-9a0a-0e59fda5fc77.png)

---

As oppossed to:

---

![screen shot 2018-05-22 at 11 51 13](https://user-images.githubusercontent.com/2676542/40355360-724a11fc-5db6-11e8-817e-f0ce4c2a7d5f.png)

**Comment by michieldenhaan** [comment]
I like the compact version better than the current one

**Comment by ChaelKruip** [comment]
> I like the compact version better than the current one

Me three!

BTW: why is there no "i" behind the last slider? I think that should tell the user that this slider is the result of the others!
