### ISSUE TITLE
Batch generation of datasets

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#116]
At the moment we can create or update multiple datasets at once in ETSource using a csv file and running ``rake import:csv_import_datasets``. ETLocal is still missing this functionality. I think it's desirable to add the following features to ETLocal: 

**1. Update database using a csv**
At the moment we can only update datasets in batch by clearing the entire database and re-seeding it. This is tedious and also means that we lose any manual user edits (unless we copy them to the seeding csv). It would be nice if we can update/migrate the ETLocal database using a csv in such a way that:
- Only the areas in the csv are updated
- Only the input/ETLocal keys in the csv get updated
- It is possible to add a source (a string of text) per value that will show up in the 'history' field
- It is possible to revert/undo the update

**2. Import updated datasets in ETSource**
Secondly, it would be nice if we can export updated areas automatically to ETSource, such that we don't have to write down the IDs of the updated datasets and run ``DATASET=<id> rake etsource:export`` for each one.

**Comment by michieldenhaan** [comment]
> I don't know what the intended desire is for this functionality? To have all the datasets in ETsource? This is still not possible as far as I'm aware.

What I meant is this: suppose that we want to add all municipalities in Friesland to ETSource. Then the preferred workflow is the following:
1. Make a csv with ETLocal inputs + source strings for all Friesland municipalities
2. Import this csv into the database/migrate the database -> the updated datasets are now accessible in ETLocal, but not yet in ETSource. 
3. Have some easy way to export all updated datasets to ETSource (not all datasets, just the ones that have been updated)

It would be very tedious if we have to go to ETLocal, click on each municipality we've just updated, write down their dataset number and run ``DATASET=<id> rake etsource:export`` for each one. Maybe the migration script can return something like "You have just updated datasets ``<ID1>, <ID2>, <ID3>, <ID4>`` etc." and extend ``rake etsource:export`` to take multiple arguments, such that we can just copy the ouput of the migration script and run `DATASET=``<ID1>,<ID2>,<ID3>,<ID4>`` rake etsource:export``

**Comment by grdw** [comment]
Hmm. I feel this can be done even easier than:

```
`DATASET=<ID1>,<ID2>,<ID3>,<ID4> rake etsource:export``
```

Namely that the CSV in the aforementioned step already contains all the (CBS) ID's of datasets you'd like to export to ETsource. So maybe change:

```
`DATASET=<ID1>,<ID2>,<ID3>,<ID4> rake etsource:export``
```

to:

```
`DATASET=<GEO_ID1>,<GEO_ID2>,<GEO_ID3>,<GEO_ID4> rake etsource:export``
```

**Comment by grdw** [comment]
I'm sorry but you can scrape that last idea 😢 - this can't work with multiple versions of a single dataset.

**Comment by grdw** [comment]
I added the batch export: https://github.com/quintel/etlocal/commit/a4272a7d8e862db198b4993fd63db940f5387856

**Comment by grdw** [comment]
I've added a generator which can update datasets with a CSV. How this works is as follows.

Let's say you'd want to change the defaults of Friesland with a CSV, run:

```
rails g default_migration updating_defaults_for_friesland 'some_file.csv'
```

This will generate a migration:

```ruby
class UpdatingDefaultsForFriesland < ActiveRecord::Migration[5.0]
  def self.up
    CSVImporter.import!(Rails.root.join('db', 'migrate', 'csv', 'some_file.csv'))
  end

  def self.down
    raise ActiveRecord::IrreversibleMigration
  end
end
```

This code can be altered but most of the time this will suffice. 

The 'csv' file has to be put into the `db/migrate/csv` folder.
