### ISSUE TITLE
Slider defaults broken in 'read only' mode

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#117]
![screen shot 2018-05-22 at 12 38 58](https://user-images.githubusercontent.com/2676542/40357630-259488ae-5dbd-11e8-9c17-7e7c081f5d91.png)

🤔

**Comment by michieldenhaan** [comment]
While you're at it, in 'read only' mode the front-end currently shows a lot of decimals. Maybe you can change this to 2 decimals?

**Comment by grdw** [comment]
> While you're at it, in 'read only' mode the front-end currently shows a lot of decimals. Maybe you can change this to 2 decimals?

I already managed to fix that!

**Comment by grdw** [comment]
Closing https://github.com/quintel/etlocal/commit/c6c981f0fd317a26f2e01e112988e843a881d269
