### ISSUE TITLE
Saving a scenario for "selwerd" in Groningen gives a bug

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etlocal#119]
One of our customers is making a dataset for Selwerd in Groningen.

When he tries to save the scenario he receives the following error message.
@michieldenhaan and @antw can you have a look at this?

![image](https://user-images.githubusercontent.com/19907658/40967740-1ec32dd0-68b4-11e8-94d7-c58a879ec38c.png)

**Comment by antw** [comment]
Both the geothermal and heat pump inputs in the screenshot appear to be blank and have no value. This seems to be the case for most (all?) regions. @michieldenhaan Do you know why this might be?

**Comment by michieldenhaan** [comment]
The default values are loaded from a database. If a new key is added to the front-end and no default value is specified for a region the field will be blank. I'll try and see if I can add the missing values to the database. For now, simply setting the blank fields to 0 will solve the error

**Comment by michieldenhaan** [comment]
Closing, created a more general issues: https://github.com/quintel/etlocal/issues/120 and https://github.com/quintel/etlocal/issues/121
