### ISSUE TITLE
Throw more readable error when ETLocal input field is blank

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#121]
Currently ETLocal gives this error. Would be nice if the error is more user-friendly, e.g. 
'The following fields are left blank: 
- Warmtegebruik geothermie
- Warmtegebruik (diepe) bodemwarmtepomp
etc.'

![40967740-1ec32dd0-68b4-11e8-94d7-c58a879ec38c](https://user-images.githubusercontent.com/32056448/41286803-0ab6ba2c-6e41-11e8-98fa-346959be602b.png)

**Comment by mabijkerk** [comment]
@noracato is this still relevant?
