### ISSUE TITLE
Clean up old datasets

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#126]
Now that ETLocal is up and running we can end support for datasets based on initializer inputs and initializer methods. We can start using ETLocal as our main tool for generating our datasets and documenting our data and assumptions.

This task is two-fold:
- [x] Convert all datasets on ETSource relying on initializer inputs and methods to graph methods (22 datasets). This means that we can clean up all code related to the initializer era.
- [x] Update the current default ETLocal values for all datasets (124 graph method datasets + 22 old datasets) such that the data on ETLocal corresponds to the data used by ETSource

**22 datasets** **using initializer inputs or methods:**

_Initializer inputs_
- [x] De Biezen (remove)
- [x] Drenthe (overwrite with new method)
- [x] Flevoland
- [x] Groningen (province) (overwrite with new method)
- [x] Noorderplantsoen (overwrite with new method)
- [x] Paddepoel Noord (keep hidden duplicate manually made)

_Initializer methods_
- [x] Zeewolde
- [x] Urk
- [x] Stedendriehoek (?, convert?, is there an ETLocal region for this?)
- [x] ‘s Heer Hendrikskinderen (remove)
- [x] Reitdiep (compare to new dataset. Use new unless differences are big)
- [x] Oostkapelle (remove)
- [x] Noordoostpolder
- [x] Lelystad
- [x] Goes (remove)
- [x] Groningen (municipality) (overwrite when differences are small, else keep hidden duplicate manually made)
- [x] Dronten
- [x] Antwerpen (make new dataset with graph methods, based on data provided by Antwerpen/DNV-GL)
- [x] Amersfoort (overwrite with new method)
- [x] Almere-Zeewolde
- [x] Almere
- [x] Baarland (remove)

**124 datasets** **using graph methods but not yet documented on ETLocal:**

_Graph methods_

- [x] All Gelderland datasets
- [x] All West- en Midden-Brabant datasets
- [x] Etten-Leur (overwrite when differences are small, else keep hidden duplicate manually made)
- [x] Zeeland
- [x] Veere
- [x] Utrecht (province)
- [x] Schouwen-Duiveland
- [x] Rotterdam
- [x] Oostkapelle
- [x] Noord-Beveland
- [x] Hengstdal
- [x] Haarlemmermeer
- [x] U10: municipalities
- [x] U10: Vijfheerenlanden en U10

**Comment by DorinevanderVlies** [comment]
Datasets which I think need "special" care:

**Paddepoel Noord**
- Empty scenario: 391535
- Relevant scenarios: 341734, 341735, 341736
- Proposal: make a hidden duplicate in ETLocal. Use old dataset (the empty scenario) to find values for Final demand houdeholds, PV on households, final demand transport, electricity supply. 
- @MartLubben 

**Noorderplantsoenbuurt**
- Empty scenario: 391540
- Relevant scenarios: 341738, 341739, 341740, 341741, 341742
- Proposal: delete old dataset and transfer scenario's to new dataset. Even though there are differences between the old and the new dataset. **I need to check this with Groningen**

**Reitdiep**
- Empty scenario: 391545
- Relevant scenarios: 361328, 360969, 355293, 355292, 355291
- Proposal: delete old dataset and transfer scenario's to new dataset. The old and the new dataset are very similar.

**Gemeente Groningen**
- Empty scenario: 391554
- Relevant scenarios: 355118,364133,356346,368337
- Proposal: this municipality does not have a dataset made using the graph method. Proposal: make this dataset first. Compare the old and the new datasets. If the differences are small use the new dataset **I will check with the municipality if small differences are allowed**. Documentation based on the scenario is called "Groninger Routekaart CO2 neutraal" and can be found on Dropbox

**Antwerp**
- This dataset needs special attention! The people using (results of scenarios made with) this dataset care a lot about consistency with their own data.
- Empty scenario: 391560
- Relevant scenarios: 790323, 819860
- Proposal: make new dataset with graph methods, based on data provided by Antwerpen/DNV-GL. My estimate of allowed differences: <1%

**Stedendriehoek**
- Empty scenario: -
- Relevant scenarios: ????
- Proposal: make new dataset by adding the seven municipalities involved: https://nl.wikipedia.org/wiki/Stedendriehoek_(gemeenschappelijk_orgaan). I am uncertain if ETLocal can deal with a region that is not on a map-layer

**Amersfoort**
- The input for this dataset was provided by E&E. 
- Proposal: this municipality does not have a dataset made using the graph method. Proposal: make this dataset first. Compare the old and the new datasets. If the differences are small use the new dataset. If the differences are "big" use input provided by E&E to make an Amersfoort dataset using the graph methods. I think E&E can help to estimate whether differences are "small" or "big"

**Comment by MartLubben** [comment]
Noorderplantsoenbuurt: Fixed after migration by @antw 
Reitdiep: Fixed after migration by @antw
