### ISSUE TITLE
Region borders are outdated

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#134]
The ETLocal map is starting to get a bit outdated. Every year some municipality/neighbourhood borders change and it looks like ETLocal is still using 2015 borders. 

E.g. ETLocal still contains the municipalities 'Vlagtwedde' and 'Bellingwedde', which have been merged into a new municipality 'Westerwolde'.

For some recently changed municipalities ETLocal shows the 2015 borders when clicking on it, but no pop-up comes up. See screenshot below for Bussum.

I've tried to figure out how these borders are defined in ETLocal, but so far to no avail. It might have something to do with a Mapbox account.

This may become relevant in the near future with some of the upcoming dataset projects.

![etlocal httpsbeta-local energytransitionmodel com 2018-08-14 17-02-12](https://user-images.githubusercontent.com/32056448/44099835-cdcebb12-9fe3-11e8-853d-661d635de123.png)
_ETLocal still contains obsolete 'Bellingwedde'_

![etlocal httpsbeta-local energytransitionmodel com 2018-08-14 17-18-58](https://user-images.githubusercontent.com/32056448/44100805-251453b2-9fe6-11e8-9dc8-2cc71ba38399.png)
_ETLocal doesn't show a pop-up when clicking on obsolete 'Bussum'_

**Comment by michieldenhaan** [comment]
The borders can be updated by uploading shape files to our Mapbox account. To make sure that the right pop-up shows up when clicking on a region the new areas have to be added to the database as well (and the old ones removed). As discussed with @antw, adding new areas is currently not supported by the csv importer to avoid errors (see https://github.com/quintel/etlocal/issues/128#issuecomment-414610444).

Since the current database contains a lot of outdated defaults, wrong commit messages, outdated area names/ids and hasn't been used yet to make a 'real' dataset, @ChaelKruip and I discussed wiping the database completely to make a fresh start. I can subsequently add the updated borders, correct areas/ids and defaults and then start adding documentation for the recent U16/Noord-Holland datasets. Do you agree with this @antw?

If so, could you:
- Make a backup of the current database
- Wipe the database
- Make a second version of the csv-importer that does allow creating new regions?

**Comment by antw** [comment]
> Make a backup of the current database
> Wipe the database

Fine with me. I'll do this once the CSV importer is adjusted and after confirming with you.

> Make a second version of the csv-importer that does allow creating new regions?

I've done this in a local branch, but have a question about workflows: at the moment we have an nl_datasets.csv file which is used to set up the datasets in a blank copy of ETSource. Do you want to get rid of that and replace it with the CSV/YAML approach we used for CSV region *updates*?

**Comment by michieldenhaan** [comment]
> Do you want to get rid of that and replace it with the CSV/YAML approach we used for CSV region updates?

I think so yes if it isn't too much work (I don't have a strong preference). I suppose that the CSV/YAML approach would be more resource efficient than the old approach?

**Comment by antw** [comment]
> I suppose that the CSV/YAML approach would be more resource efficient than the old approach?

I doubt it to be honest. The old *CSV importer* – used to update datasets with new information – created a ton of commits for each dataset, but the *dataset importer* – used to fill a blank database with initial values – creates only one commit per dataset with the message "Initial value Quintel CBS". Using CSV/YAML may well be slower, but it allows you to create multiple commits if that's what you want.

If we use the CSV/YAML approach, the structure of the CSV and YAML would be the same as we use to update datasets, with the exception that the CSV must also include an `area` column to set the name of each dataset *(side-note: perhaps that should be called `name` instead of `area`?)*. If this is satisfactory, I can make it happen.

**Comment by michieldenhaan** [comment]
Ok, sounds good! I'm happy with the CSV/YAML approach. How about ``geo_name`` (to pair with ``geo_id``)?

**Comment by antw** [comment]
I merged this, then reverted the change and restored the dataset-importer branch. The CSV files don't contain all the information needed to initialise a new dataset; was it expected for the dataset importer to fill in the blanks from a scaled graph?

**Comment by michieldenhaan** [comment]
Closing: https://github.com/quintel/etlocal/commit/2643ebaa2cae42185da8be8c0bfaa31d55c9d0a9
