### ISSUE TITLE
Choices dataset defaults

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#138]
I'm currently preparing the ETLocal defaults for all provinces/municipalities/districts/neighbourhoods and face a few choices:

- Since there's no data on industry/agriculture for districts and neighbourhoods (wijken/buurten), I was thinking about setting ``has_industry`` and ``has_agriculture`` to false for these datasets.

- Commit messages: in Dutch or English?

- Decrease step size of grid expansion (notifying @MartLubben, @jorisberkhout). The default step size for grid expansion in the NL dataset is roughly 100 residences (lv), 1000 residences (mv) and 10000 residences (hv). For most regional datasets this is way too big (e.g. a lot of neighbourhoods have less than 10 residences). To get meaningful grid expansion costs, I think we should decrease the step size for local datasets.
E.g.: 

  - provinces equal to NL 
  - municipalities 10 residences (lv)/100 residences (mv and hv) (smallest municipalities have a couple of hundred residences)
  - district 10 residences (lv/mv/hv)
  - neighbourhood 1 residence (lv/mv/hv)

Curious to hear yall's thoughts!

Notifying @ChaelKruip, @AlexanderWirtz, @marliekeverweij, @DorinevanderVlies

**Comment by jorisberkhout** [comment]
I agree with your suggestion for the step sizes @michieldenhaan . One question, do the costs of the steps scale as well?

**Comment by michieldenhaan** [comment]
> One question, do the costs of the steps scale as well?

Yes! Thanks for your input everyone, closing this.
