### ISSUE TITLE
Change commit messages?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#143]
As @MartLubben rightfully pointed out, some of the current commit messages are a bit cryptic. This makes ETLocal less useful to share with customers. @antw Is it possible to update existing commit messages or does that mean we have to reseed the database again?

Below the relevant messages:

_Old message:_ Aanname Quintel
_New message:_ Geen data beschikbaar

_Old message:_ Schatting Quintel
_New message:_ Schatting Quintel. Zie https://refman.energytransitionmodel.com/publications/2098 voor een overzicht van onze schattingsmethoden.

_Old message:_ Quintel estimate. No 2016 data available. Estimated based on total energy/electricity/gas use reported by Klimaatmonitor and/or average data from previous years. See: https://klimaatmonitor.databank.nl/Jive?workspace_guid=7d85d44f-1169-4d6e-bec3-b0307f9296f5 And: https://klimaatmonitor.databank.nl/Jive?workspace_guid=daddc06a-6d9e-4748-b1be-c66ca6aa973c
_New message:_ Geen data beschikbaar voor 2016. Bijschatting Quintel op basis van het totale energie-, elektriciteits- en gasgebruik in de regio (volgens Klimaatmonitor) en/of data van de afgelopen vijf jaar. Zie https://klimaatmonitor.databank.nl/Jive?workspace_guid=7d85d44f-1169-4d6e-bec3-b0307f9296f5 en https://klimaatmonitor.databank.nl/Jive?workspace_guid=daddc06a-6d9e-4748-b1be-c66ca6aa973c

**Comment by antw** [comment]
> @antw Is it possible to update existing commit messages or does that mean we have to reseed the database again?

We can do this with a database migration without needing to start over. I can stick it on the todo list 😜: is it needed by a particular date?

**Comment by MartLubben** [comment]
>is it needed by a particular date?
It would be nice to have for next week Wednesday (14:00, client meeting) , it would be quite necessary Tuesday the 6th of November (10:00, a very sceptic client meeting). :)
