### ISSUE TITLE
Swap building lighting shares?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#153]
I found a small mistake in the building lighting shares. The shares for 'Fluorescent tube' and 'High-performance fluorescent tube' are mixed up for all datasets:

`buildings_final_demand_for_lighting_electricity_buildings_lighting_standard_fluorescent_electricity_parent_share` is 0.05 -> should be 0.94
`buildings_final_demand_for_lighting_electricity_buildings_lighting_efficient_fluorescent_electricity_parent_share` is 0.94 -> should be 0.05

@antw is it easy to swap these shares directly in the database for all datasets? If not, I can make a migration.

Edit: Some shares are corrected already. So with 'swap' I mean: standard fluorescent should be 0.94 for all datasets, efficient fluorescent should be 0.05 for all datasets.

**Comment by antw** [comment]
> Edit: Some shares are corrected already.

I think it would be safe to adjust the initial commits for Quintel datasets rather than adding new commits or dataset edits; does that sound okay to you?
