### ISSUE TITLE
Share-sliders housing stock should update number of houses correctly

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#155]
@michieldenhaan and I just found out that the new housing stock sliders on ETLocal on the https://github.com/quintel/etlocal/tree/heat_project branch do not always update the number of houses for each housing type correctly. 

When we only touch one housing type slider, then the number of houses for each housing type do not add up to the total number of houses. We get the following error:
![screen shot 2019-01-15 at 15 56 30](https://user-images.githubusercontent.com/32833996/51188593-900ba780-18de-11e9-8ef2-ec87ad538c39.png)

However, when we touch every housing type slider, the number of houses are correctly updated.

**Comment by antw** [comment]
@marliekeverweij Is there a copy of the ETLocal database with this dataset I can use to test? I'm having a hard time reproducing this due to missing sparse graph queries in my local copy of ETSource.

**Comment by marliekeverweij** [comment]
I've uploaded a copy of my ETLocal-database on Dropbox in the heat/biomass project folder (Development/Databases/Heat:biomass-project (WIP))

**Comment by antw** [comment]
The problem seems to be that ETLocal's front-end treats the inputs as percentages with no decimal places, whereas the default values for most (all?) groups have many decimal places.

For example, the default values for Zeewolde are:

| House type | Percentage |
| --- | --: |
| Apartments | |
| Apartments | |
| Apartments | |

Apartments:
* 
*
*
*

**Comment by michieldenhaan** [comment]
SGTM!

**Comment by antw** [comment]
> Yes, let's go for the simple fix!

Okay! It's now on the `master` branch (because it wasn't specific to heat) but it can be cherry-picked to `heat_project` if it's necessary for your work on that.
