### ISSUE TITLE
It should be possible to see the dataset of a province in ETLocal

### ISSUE THREAD

**Issue by MartLubben** [quintel/etlocal#160]
It is now not possible to see the dataset of a Province in ETLocal.

**Comment by michieldenhaan** [comment]
I can add a map layer for provinces. However, a few provinces are still missing in the database, maybe we should add those first?

Notifying @marliekeverweij

**Comment by marliekeverweij** [comment]
Yes let's do that! I will let you know when it's done

**Comment by AlexanderWirtz** [comment]
Hey @michieldenhaan (and @marliekeverweij), for the Systeemverkenning Groningen and Drenthe project it would be really great if we can somehow see provincial datasets in ETlocal. I do see that the Groningen  and Drenthe datasets are quite old. We will need to update that to 2016. 

For the project we will most likely make a joint dataset for Groningen and Drenthe. How can users see select such datasets on ETlocal? We would like to use ETlocal as a way of documenting such datasets, but I do not see if this is possible right now

**Comment by michieldenhaan** [comment]
The Groningen and Drenthe datasets have been updated to 2016 with the recent heat merge. I can add a map layer to make them 'clickable' in ETLocal. For a joint dataset we can add yet another map layer, tho we have to be a bit careful not to add too many
