### ISSUE TITLE
Map/layers sometimes stop loading at all

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#167]
With the internet connection at the office, the municipality layer loads pretty quickly most of the time. But with lower internet speeds it doesn't, as @AlexanderWirtz has experienced yesterday. Is there some way to speed this up?

**Comment by michieldenhaan** [comment]
A related problem is that the map/layers sometimes stop loading at all and you have to refresh the page to try again. Maybe the culprit is the underlying map from Openstreetmap (rather than the province/municipality layers) which contains a lot of details (roads, shadings, street names)

**Comment by AlexanderWirtz** [comment]
> A related problem is that the map/layers sometimes stop loading at all and you have to refresh the page to try again.

Indeed, it is not the speed of loading, but that it stops loading altogether until you reset.

**Comment by marliekeverweij** [comment]
@antw @noracato do you have an idea how to fix this issue? Should we use a different map layer as Michiel suggests?
And do you have an idea of the time it would take to fix this issue?

More and more clients are interested in ETLocal, so would be really cool if it would actually work!
_____

FYI: notes of Nora about ETLocal that I found on BC:
- ETLocal relies on Virtus for most Interface models. Virtus has been discontinued as of 19/04/2019
- Version control is nice but may make it slow
- OpenStreetMap issue?

**Comment by antw** [comment]
> do you have an idea how to fix this issue? Should we use a different map layer as Michiel suggests?

I used to experience this issue when I ran ETLocal on my own machine without the correct Mapbox credentials. It might be worth checking that the Mapbox account is still active (I have the API key used by ETLocal, but not the username/password for the account).

**Comment by redekok** [comment]
I experienced the layers to load better when running ETLocal on my local machine lately.. 

Furthermore, I've recently heard someone say that mapbox's server is often overloaded during the day (during week days). Not sure how true this claim is though.

**Comment by michieldenhaan** [comment]
> It might be worth checking that the Mapbox account is still active 

I use it semi regularly to add new areas to the map layers. I'll send you the credentials

**Comment by antw** [comment]
What I've figured out so far:

* ETLocal has "layers", which correspond with "tilesets" in Mapbox. These define the boundaries of provinces, regions, municipalities, and neighbourhoods.

  ![Screenshot 2020-09-16 at 14 55 04](https://user-images.githubusercontent.com/4383/93347167-b066d480-f82c-11ea-8953-001e5f950adf.png)

* The map in ETLocal is made up of tiles. For example, the visible map might require loading nine tiles `{A-C}{1-3}`:

  ```
  +--------------+
  | A1 | A2 | A3 |
  | -- + -- + -- |
  | B1 | B2 | B3 |
  | -- + -- + -- |
  | C1 | C2 | C3 |
  +--------------+
  ```

  Not only is the background map loaded using many tiles, but the layers for provinces, etc, are also loaded as lots of separate tiles.

* We use a library called OpenLayers which fetches tiles from Mapbox.

* Mapbox is returning 404 (Not Found) errors when ETLocal tries to load tiles for our custom layers (municipalities, regions, etc).

* After 16 errors have occurred, new map tiles are no longer fetched from Mapbox.

### Layer extents

The map layers have an "extent" which define the boundaries (north/south, east/west) of the layer. It looks like Mapbox returns 404 errors if OpenLayers requests a tile which doesn't exist. For example, if we try to load tiles for the "regions" layer 
 outside the Netherlands, we get a 404.

As far as I can tell, the west-most boundary was incorrect; it was previously somewhere parallel with the west coast of Spain/Portugal:

![Screenshot 2020-09-16 at 14 39 04](https://user-images.githubusercontent.com/4383/93345420-b3f95c00-f82a-11ea-994a-aa98faa0c515.png)

This means ETLocal was trying to load tiles for NL municipalities outside of NL, resulting in 404s. [I've adjusted this](https://github.com/quintel/etlocal/commit/a62e73f1746bd187b2ea378136856b66beff4fe9).

### Still not fixed?

However this doesn't eliminate all the 404s. The extent we define looks something like this:

![Screenshot 2020-09-16 at 14 48 04](https://user-images.githubusercontent.com/4383/93346563-05eeb180-f82c-11ea-977f-b72ab2a04490.png)

You can see that it covers an area of Belgium and Germany. I get 404 errors when trying to load tiles for those areas. Again, this is what the tileset looks like on Mapbox:

![Screenshot 2020-09-16 at 14 55 04](https://user-images.githubusercontent.com/4383/93350816-eefe8e00-f830-11ea-81f0-9d5679e43afa.png)

There's no data outside of the Netherlands. My guess is ETLocal/OpenLayers is trying to load tiles for these areas, and get a 404 back from Mapbox.

Maybe there's something we can do with the tilesets to say "there's no data here" and prevent the 404s, or perhaps there's something we can configure in Mapbox?

### Fixing map tiles not loading

Fortunately, resolving the 404s is not too pressing. I've updated OpenLayers from v4.2.0 to v4.6.5 and it now apparently continues loading even after 16+ errors. The latest version of OpenLayers is v6.4.3, but decided using the latest v4 would be the safest fix for the short term.

**Comment by ChaelKruip** [comment]
> Fortunately, resolving the 404s is not too pressing. I've updated OpenLayers from v4.2.0 to v4.6.5 and it now apparently continues loading even after 16+ errors. The latest version of OpenLayers is v6.4.3, but decided using the latest v4 would be the safest fix for the short term.

Great! Until we fix this nicely, the interface is operational again then?

**Comment by michieldenhaan** [comment]
> As far as I can tell, the west-most boundary was incorrect; it was previously somewhere parallel with the west coast of Spain/Portugal

The reason for this is that Northern Ireland is also on ETLocal. In order for the NI feature to load, the layer extent had to be broadened. Similarly, we have a few regions in Belgium (e.g. Oostende, Antwerp).

One thing that might make ETLocal faster is trying to simplify the map. Currently it loads all kinds of information we don't need, such as motorways, national parks etc. Maybe we can disable all that and only load our own custom layers with a simple grey background (or some other colour)?

**Comment by antw** [comment]
> The reason for this is that Northern Ireland is also on ETLocal. In order for the NI feature to load, the layer extent had to be broadened.

Thanks, I've reverted that change. I didn't notice that the boundary for the provinces layer extended that far west.

> One thing that might make ETLocal faster is trying to simplify the map.

I'm not sure that getting rid of this kind of data will make any difference to the speed of ETLocal. The map tiles, with roads, forests, etc, are delivered to the browser as an image from Open Street Map. I expect that these are pre-compiled, but either way it doesn't seem to incur any performance penalty for us. Here's one such tile, exactly as it comes from OSM:

![2692](https://user-images.githubusercontent.com/4383/93370152-4c520980-f848-11ea-8dfe-10b2dccf8df2.png)

**Comment by marliekeverweij** [comment]
Very nice that the map layers are loading again! I just took a few minutes to test and did not run into any loading issues, even the neighborhood datasets load very quickly.

But if I understand correctly we want to get rid of all 404 errors and these still occur

**Comment by michieldenhaan** [comment]
I think we can close this one, it all works very smoothly now!
(Re-open if you disagree)
