### ISSUE TITLE
Create Live version of ETLocal

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etlocal#173]
I show more and more people all the cool and useful stuff that is in ETLocal. For now I give them the link to the Beta version, but I can imagine that we want to create a Live version in case we further develop ETLocal.

@antw , how much work would it be to create a Live version of ETLocal?

**Comment by ChaelKruip** [comment]
> @antw , how much work would it be to create a Live version of ETLocal?

I'm curious about this too!

**Comment by antw** [comment]
> @antw , how much work would it be to create a Live version of ETLocal?

Not long. Maybe a day or two to configure the server, backups, sort out deployments and databases and so on.

**Comment by marliekeverweij** [comment]
@antw we have decided to go live with ETlocal and delete the beta-version! We want to use data.energytransitionmodel.com 
Do you have time to make this happen?

**Comment by antw** [comment]
It's done.

* Production: https://data.energytransitionmodel.com
* Staging: https://beta.data.energytransitionmodel.com (the old "beta-local" address will redirect)

Data from staging has been copied over to production. The fate of staging is up to you, but if we're continuing development I think I'd prefer that we kept it (even if only for testing).

**Comment by marliekeverweij** [comment]
> Data from staging has been copied over to production. The fate of staging is up to you, but if we're continuing development I think I'd prefer that we kept it (even if only for testing).

I think it's good to start a discussion here on how we want to use the production and staging server of the ETM Data Manager. And also IF we want a staging server. I would say yes, I agree with you that it's nice to have a server for testing before going live, especially when more people will be using it. However, I do think it's tricky to have two versions of the same dataset database.

Therefore, I would propose the following process:
- Use the **staging server** for how we've used ETLocal up to now:
  - Update datasets here: directly through the interface or with a migration
  - Export datasets to ETSource from here. So the staging server contains the most up-to-date datasets! It's often the case that you directly want to export a dataset after updating it, so exporting from the production server would not be desirable as it takes time to deploy the update to the live server.
  - Update interface elements / texts here

- The **production server** is then mostly used by our users to view the sources of a dataset.
  - When do we want to deploy the ETM Dataset Manager (match staging server with production server)? We could do this together with the rest of the ETM (once a month) or do this manually. Maybe manually is the best option as you do not want to be out of sync with the datasets in the ETM. Or we could deploy after each data migration? What would you propose @noracato, @antw, @michieldenhaan?
  
 @everybody with an option on this topic, let me know what you think of this proposal

**Comment by antw** [comment]
> So the staging server contains the most up-to-date datasets! [...] When do we want to deploy the ETM Dataset Manager ...

I might be misunderstanding your suggestion, but I'm not sure about this. The customisations to datasets are stored in a database. We can't just create a dump of the staging DB and import it into production without overwriting any and all other changes which may have occurred on the production server.

We cannot selectively import only the dataset data, because relations to other parts of the database would become invalid: for example if a dataset commit were attributed to user 100, that might be a completely different user on the production server.

I think the only way this is doable is if production is *completely* read-only. No-one would be allowed to make edits to production. That includes not only adding and editing datasets, but also preventing people from creating accounts. I'm fine with this if this is the direction you want to take. I'm not terribly keen on having to export/import databases since we *just finally* stopped having to do this in ETModel (thanks to YModel), but... 🤷‍♂️

**Comment by marliekeverweij** [comment]
> I think the only way this is doable is if production is completely read-only. No-one would be allowed to make edits to production. That includes not only adding and editing datasets, but also preventing people from creating accounts. I'm fine with this if this is the direction you want to take. 

Good idea, I would be in favour of this. This way there will be a clear distinction between production and staging. Production is for users to view the datasets, staging is for us to test and import/edit/export datasets.

I am afraid that without this distinction it will be unclear which dataset version is the latest.

**Comment by marliekeverweij** [comment]
@noracato @michieldenhaan @AlexanderWirtz and I discussed this topic again last week. We prefer to use the production and beta server in the following manner:
- [Production](data.energytransitionmodel.com) is the environment that is used by **modellers**. Datasets on production are always the synced with the datasets in the ETM (this is especially important when we have the link between ETM + Dataset Manager). On production you can:
  - update dataset values (change database) + export datasets to ETSource
  - update [interface elements](https://github.com/quintel/etlocal/tree/master/config/interface_elements) -> often you want to add an interface element to ETLocal (after an ETM improvement, for example for heat networks) and after that you directly want to export all datasets including the new input value
  - update texts / [locales](https://github.com/quintel/etlocal/tree/master/config/locales)
- [Beta](https://beta.data.energytransitionmodel.com/) is the environment that is used by **developers**. Here we can test new features: search functionality, new buttons, lay-out of headers etc. When beta is deployed to production, then the updates to the [interface elements](https://github.com/quintel/etlocal/tree/master/config/interface_elements) and [locales](https://github.com/quintel/etlocal/tree/master/config/locales) should first be incorporated in beta. The database on production should not be overwritten with the database on beta.
