### ISSUE TITLE
Should we create a map layer for RES-regions?

### ISSUE THREAD

**Issue by redekok** [quintel/etlocal#177]
Currently, there are 3 ETLocal datasets for RES-regions. However, there is no map layer yet for RES-regions. Should we create a new map layer yet, since we might want to add more RES-region datasets in the future?

**Comment by michieldenhaan** [comment]
Good idea! However, I think it should be the other way around: we can add a new map layer as soon as all the regions of that layer are in the database, to avoid that the user can click on 'empty' regions.

**Comment by redekok** [comment]
Good point! Since we know which municipalities are covered by which RES-regions, it doesn't seem like too much work to create datasets for all the RES-regions (1 or 2 hours maybe?). I could work on that in a spare moment.
