### ISSUE TITLE
Move the dataset combiner service to the master branch

### ISSUE THREAD

**Issue by redekok** [quintel/etlocal#178]
On the `dataset-amalgamator` branch, the [dataset combiner](https://github.com/quintel/etlocal/blob/dataset-amalgamator/app/services/dataset_combiner.py) service exists. This doesn't really seem to be a sustainable solution. What changes/improvements should we make to the script in order to move it from the current branch to the `master` branch?

Notifying @ChaelKruip

**Comment by michieldenhaan** [comment]
The branch is not intended for merging. The service is in Python, not Ruby and primarily written as an exercise. If time permits I can clean it up a little bit and move it to https://github.com/quintel/modeling_experiments/.
