### ISSUE TITLE
Integrate replace_time_curves.py script in etsource:export script

### ISSUE THREAD

**Issue by redekok** [quintel/etlocal#179]
When exporting a dataset from ETLocal to ETSource by running `rake etsource:export DATASET=<ID1>,<ID2>,...`, we often have to replace the corresponding time curves by zeros. Currently, we use a local script (`replace_time_curves.py`, created by @michieldenhaan) to perform that action afterwards. Would it be a possibility to integrate this functionality in the `etsource:export` script? It would be nice if you could (optionally) indicate in the command line what time curves you want to adopt for the current dataset. For example by running `rake etsource:export DATASET=<ID> REPLACE_TIME_CURVES_BY=<ID>`. 

@michieldenhaan @antw What are your thoughts on this?

Notifying @marliekeverweij

**Comment by michieldenhaan** [comment]
Yes, very good idea but I guess the priority is low. This is being discussed in more detail here: https://github.com/quintel/etmodel/issues/2703
