### ISSUE TITLE
Transforming editable attributes to attributes in and .ad file

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#21]
In the current interface it's possible to edit 6 variables of a dataset. With those variables a dataset can be edited. These editable attributes (which we'll call `etlocal-attributes` for the sake of clearity) will be translated into `ad-attributes`. This has to be done through analyzes.

---

### 6 `etlocal-attributes`:

- Electricity consumption (average of a single household) in kWh
- Gas consumption (average of a single household) in m<sup>3</sup>
- Roof available for pv (???) in m<sup>2</sup>
- Number of cars
- Number of inhabitants
- Number of residences

---

### 1. Precursors

Calculate total electricity consumption:

```ruby
# Ruby
def total_electricity_consumption
  electricity_consumption * 3.6e6 * number_of_residences # J
end
```

Calculate total gas consumption:

```ruby
# Ruby
def total_gas_consumption
  gas_consumption * 3.76812e16 * number_of_residences # J
end

```

### 2. Electricity carriers

Electricity carriers are split up into multiple groups.

These groups are divided into multiple segments and subsegments.

- Space heating (7.22%)
   - Space heater combined (80% of gas after cooking)
   - Air heat pump (73.0663 MJ * HH)
   - Ground heat pump (331.0773 MJ * HH)
   - Space heater electricity (rest)
- Warm water (5.15%)
   - Water heater combined (20% of gas after cooking)
   - Air heat pump (18.26657225 MJ * HH)
   - Ground heat pump (82.769337 MJ * HH)
   - Electric boiler (rest of elec)
- Cooling (7.22%)
   - Ground heat pump (73.2427869858809 MJ * HH (or (1909 TJ / #households_nl) * HH))
   - Airco (rest)
- Cooking (3.09%)
   - Resistance (9.73% of elec)
   - Halogen (71.37% of elec)
   - Induction (18.89% of elec)
   - Gas ((total_elec_for_cooking/28.3)*71.7)
- Lighting (13.4%)
   - LED (0.34%)
   - Efficient fluorescent (83.33%)
   - Incandescent (16.33%)
- Appliances (63.92%)
   - Dishwasher (8.06%)
   - Fridge/freezer (22.58%)
   - Washing machine (8.06%)
   - Clothes dryer (11.30%)
   - Television (14.52 %)
   - Computer and media (19.36%)
   - Vacuum cleaner (4.83%)
   - Other (11.30%)

### 3. Gas carriers

Gas carriers are determined from the point of gas usage of electricity cooking. 

The demand of the total cooking electricity makes up 28.3% of all the cooking. The rest of the demand (71.7%) is gas. So:

```ruby
# Ruby

COOKING = { gas: 71.7, electricity: 28.3 }

def total_gas_demand_cooking
  (total_electricity_demand_of_cooking * COOKING[:gas]) / COOKING[:electricity]
end
```

The rest of the gas is used for a `cv` (Hot water) and for a `cv` (Space heating) (Showering and heating your house effectively) in a (1/5 HW, 4/5 SH ratio).

```ruby
# Ruby

def demand_of_cv_hot_water
  (total_gas_demand - total_gas_demand_of_cooking) * 0.2
end
```

```ruby
# Ruby

def demand_of_cv_space_heating
  (total_gas_demand - total_gas_demand_of_cooking) * 0.8
end
```

#### Transport

We scale the total UD from the NL dataset to a value per car (15066.47):

UD  = 15066.47 MJ * number_of_cars

#### Solar PV

We ask the user to enter the average roof surface available per HH, which we multiply by the number of households, and divide by 10ˆ6 to get the total available surface in km2. 

#### Energy sector
To ensure the national energy mix, we want to give local datasets the national power sector. The CHP's, however, do produce power for the entire country, but not heat. Therefore, we transfer their capacity to a power plant using the same energy carrier. Scaled per household, the new values for the number of power plants become:

energy_power_combined_cycle_network_gas: 	   0.0000020124185 * HH
energy_power_ultra_supercritical_coal:	           0.0000003273924 * HH 
energy_power_ultra_supercritical_cofiring_coal:   0.0000001556091 *. HH
energy_power_supercritical_waste_mix	            0.0000017866586 * HH

#### Non variable inits
Some initializer inputs are needed for excluding sectors and technologies. For a complete list, see:
https://gist.github.com/BerendSmits/b1f295b066ebb7a4254d0e10655dfdef

#### Area attributes
Some area attributes that come out of the rake task, need to be changed. These are:

- has_agriculture = true => - has_agriculture = false
- has_buildings = true => - has_buildings = false
- has_industry = true => - has_industry = false
- has_other = true => - has_other = false
- number_of_buildings = scaled_value =>  - number_of_buildings = 0
- number_of_cars = scaled_value => - number_of_cars = input_value
- number_of_inhabitants = scaled_value => -number_of_inhabitants = input_value

### 5. FD -> UD

Initializer inputs always use UD, therefore we need to convert FD to UD as a last step. UD = FD * eff, for a list of all efficiencies, see:

https://gist.github.com/BerendSmits/726c974871c7545b281ef6f4cb415038

### 6. Shares and total UD's

The total UD per group must be determined, and then every UD per technology can be transferred into a share (note: 0<share<100).

For space heating and cooling, the UD's need to be divided between old- and new houses, because the init's which set both don't work. We shall use the national division keys for the prototype, later the option can be added to make the distinction. 

For now: 
UD_oldhouses = 92.62% of total  
UD_new_houses = 7.38% of total

This goes for both cooling and space heating.

**Comment by BerendSmits** [comment]
As this analysis is built now, it would be possible for a user to get negative UD's and shares for some of the 'leftovers technologies'. We can write a message to a user saying they are doing something weird (not enough electricity mostly), or we can put the negatives to 0. I would have a preference for the latter, and so does @grdw I think, what would you say @dennisschoenmakers?
