### ISSUE TITLE
Ideas for expanding analysis

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etlocal#24]
We have built a working prototype of a simple analysis, which only accounts for households and transport, and uses a lot of assumptions. To finetune the analysis and add other sectors, we can think of expansions to ETlocal. This issue is a first idea of the possibilities, everyone feel free to add and comment. 

Households sector:

Heatpumps:
We now scale the amount of heatpumps per household from the national total. Quite often this number would be incorrect, for instance in Amsterdam you can easily bet there will be no ground heat pumps. I would propose the possibility to add the total amount of heatpumps for the area, per type (this will also make it easy to just set them all to 0). 

Old/new houses ratio
We use the national ratio for old and new houses, but this off course does not work for every neighbourhood, and people might know the actual ratio (this could just be all old or all new for a lot of neighbourhoods). We can add the option of entering this ratio. That would also mean some things change in the setting of the useful demand for space heating and cooling, since that is split in old and new. Possibly we can also let people edit the insulation coeff. 

Buildings sector

The buildings are now completely ignored. We should think about in what way we want to add them, and where the data should come from. We could think of a square meter scaling, allowing people to enter the surface of local utilities, or maybe a number of companies per sector, and we add some sort of typical usage for a company in a certain sector. 

Industry

For adding industry, I would propose to let people enter a percentage of the national total of this industry. This data is available from the klimaatmonitor, and our initializer inputs let us scale sectors quite easily. 
Actually letting people enter usages per sector or per carrier is too complicated for ETLocal I think. 

Agriculture

For agriculture, using land (or greenhouse) surface is probably the best way to scale usage. Or number of animals in the cattle sector :monkey: :chicken: :cow2: :cow2: :see_no_evil:

Transport 

We're now only adding cars to the ETM, which we scale by the amount of cars registered in the area. Adding trains, trucks, or navigation is possible, scaling either by number of households, inhabitants or companies registered.

**Comment by grdw** [comment]
> I would propose the possibility to add the total amount of heatpumps for the area, per type

Per type, you mean 'cooling', 'space-heating' and 'hot-water'? Or also the specific sub-types? 

> For adding industry, I would propose to let people enter a percentage of the national total of this industry. 

So if you have no industry, you'd say 0%? 

I assume that the `has_industry` flag automatically needs to be set to true if this percentage is larger than 0.

**Comment by BerendSmits** [comment]
> Per type, you mean 'cooling', 'space-heating' and 'hot-water'? Or also the specific sub-types?

I would say the number of ground- air- hybrid pumps etc.. and then use the same number for both space heating, cooling and hot water. 

> So if you have no industry, you'd say 0%?

We can make separate option for no industry at all, that would be a bit cleaner I think. This expansion is  more for scaling industry per sector

> I assume that the has_industry flag automatically needs to be set to true if this percentage is larger than 0.

Yesss

**Comment by BerendSmits** [comment]
For the building analysis, @ChaelKruip proposed to scale by surface. I checked what the influence of the AREA attribute number of buildings is, this seems to only affect the costs of isolation. The scaled value will be ok I think, and we can use typical demands per surface.

**Comment by BerendSmits** [comment]
Some are now implemented, the other are further discussed in https://github.com/quintel/etlocal/issues/53
