### ISSUE TITLE
Some numbers are displayed as NaN in the front-end

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#244]
See screenshot. Front-end shows NaN even though a number is set (and is also in the database). Biogenic waste share is set to 0.59.

![image](https://user-images.githubusercontent.com/32056448/96227128-ef0abe80-0f93-11eb-8d14-d4e434985499.png)

**Comment by antw** [comment]
I've redeployed ETLocal with the latest version of ETSource. The sliders and values are working correctly now.

When a slider is not considered "whitelisted" (because ETLocal and ETSource are out-of-sync), it's value is no longer sent to the front-end. This results in the NaNs you saw.
