### ISSUE TITLE
Add short descriptions for all inputs

### ISSUE THREAD

**Issue by noracato** [quintel/etlocal#253]
Right now some inputs have a detailed description and some do not. The goal is to add explainations to all inputs in the locale files `nl_` and [`en_dataset_edits.yml`](https://github.com/quintel/etlocal/blob/840b24e97551333619ca264abb1a81f8653f1d55/config/locales/en_dataset_edits.yml#L118).

To not get unreadable locale files I'll add support for categorising the explainations per group/sector (whichever one is preferred).

- [x] Add support for categorising explaination in locale files

I'll put a checklist here to keep track of the sectors that are done, so all of us can take care of some sectors when we have spare time:

- [x] General
- [x] Households
  - [x] Demand
  - [x] Supply
  - [x] Advanced
- [x] Buildings
  - [x] Demand
  - [x] Supply
  - [x] Advanced
- [x] Transport
  - [x]  Road vehicles
  - [x] Trains
  - [x] Ships
  - [x] Planes
  - [x] Advanced
- [x] Agriculture
- [x] Industry
  - [x] Metal
  - [x] Chemical
  - [x] Food
  - [x] Paper
  - [x] ICT
  - [x] Other
- [x] Energy Production
  - [x] Renewable
  - [x] Fossil
  - [x] Heat
  - [x] FLH
- [x] Other

**Comment by noracato** [comment]
I added support for putting the descriptions in a locale subfolder on the branch [`descriptions-inputs`](https://github.com/quintel/etlocal/tree/descriptions-inputs). You can work further on this issue on that branch 😄

**Comment by marliekeverweij** [comment]
@michieldenhaan I went through ETLocal and have added descriptions everywhere where I think it's necessary. Do you have time to also go through and see if we are missing some?

Note: we haven't focused on the English descriptions for now! When were done with the Dutch texts, then we could translate all texts at once to English.
