### ISSUE TITLE
Replace geographical search with fuzzy dataset_name search

### ISSUE THREAD

**Issue by noracato** [quintel/etlocal#255]
The current search function uses a geographical database for NL. This means that it picks up all kinds of regions/streets/objects etc. not available in ETLocal. Also it means that the search function cannot find regions outside NL. We could replace this with a simple search (loosely) matching the region names in our database and/or a menu that allows you to select regions per country / per classifications (municiaplity, RES, province etc.)

This function should highlight or directly open the searched dataset.

@michieldenhaan, @marliekeverweij, @AlexanderWirtz did we decide already if we wanted to go with the _type it_ search, or with a dropdown?

**Comment by michieldenhaan** [comment]
> did we decide already if we wanted to go with the type it search, or with a dropdown?

I think the main consideration is how much time it takes. If a fuzzy search can be done in 1-2 days that sounds like a good fix. If it takes (much) more time we may want to consider investing that time in a different interface
