### ISSUE TITLE
It should be possible to delete values

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#258]
Currently it is not very straightforward to delete information. IMO it should be possible for Quintel users to delete 'dataset_edits' via the front-end. This helps us keep the update history clean (and hence improves ETLocal's useability). It happens quite often that the wrong information is entered/has been supplied by clients, leading to a lot of corrections in the history field.

Atm I sometimes remove erroneous dataset edits using a [migration](https://github.com/quintel/etlocal/blob/master/db/migrate/20200722143445_correct_zh.rb), which is cumbersome.

**Comment by noracato** [comment]
Can I ask you if you even want this history feature in the first place? These DatasetEdits get a lot of complaints. Or do you like the idea of a version history, and just want it a bit more user friendly?

**Comment by michieldenhaan** [comment]
The latter. I think version controlling is very useful, as long as we can keep it clean and concise

**Comment by noracato** [comment]
@mabijkerk can I close this issue, or you prefer we keep it around?
