### ISSUE TITLE
A new name!

### ISSUE THREAD

**Issue by noracato** [quintel/etlocal#263]
With the relaunch of etlocal, we feel it also needs a new (catchy) name.

Ideas:

- **ETM Dataset Generator** - this could also be a subtitle
- **Odysseus** - with the above subtitle - Journey through datasets of the complicated energy transition, also goes nicely with the map
- **ETM Regional Datasets** - nice and to the point
- **ReGen** - sounds like 'region', but has 'generator' in there as well

Please add to this list if you can think of another name!

**Comment by marliekeverweij** [comment]
A few more ideas that focus on the 'documentation' aspect:

- ETM Dataset Documentation
- ETM Regions Database

**Comment by AlexanderWirtz** [comment]
- ETM Dataset Manager

**Comment by noracato** [comment]
ETData - _Data Manager for Regions_

**Comment by noracato** [comment]
I'll make some header mockups for the discussed title (ETData) and some other high rated options and will post them here!

**Comment by antw** [comment]
> ETData - Data Manager for Regions

This may be a controversial opinion, but I've never been a huge fan of the "ET" prefix. I think it makes _some_ sense for internal names (ETModel, ETFlex) but not so much when used publicly.

* ETModel is just Energy Transition Model (Pro).
* ETFlex is the Energy Game.
* ETMobile is the Mobile Game.
* ETMoses (eventually) became the Stakeholder Analysis.

I like "Odysseus" for being short and sweet (and catchy), though I can imagine there will be frequent misspellings. "ETM Dataset Manager" is the one that stands out to me. Its a bit of a mouthful, but it describes the app quite well.

My suggestion is "Keystone":

> * the wedge-shaped piece at the summit of an arch, regarded as holding the other pieces in place.
> * something on which associated things depend:
