### ISSUE TITLE
Do we want to change all texts to match with the goal of our first milestone: a read-only version?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#270]
At the moment almost all texts start with: "In this tab you can _specify_ ...." 

However, we first want to create a read-only version where users can only read the input data and have a look at the sources. I think we should change all texts to something like: "In this tab you can _see_ the data ..."

What do you think @michieldenhaan @noracato @AlexanderWirtz ?
![Screenshot 2021-02-26 at 10 02 41](https://user-images.githubusercontent.com/32833996/109279213-c59f5080-7819-11eb-90e9-8a9a639bef9c.png)

**Comment by AlexanderWirtz** [comment]
I say no. Anyone brave enough to attempt it will contact us eventually

**Comment by michieldenhaan** [comment]
I actually do like this suggestion. The main use case for the foreseeable future is that we can refer users to it to find background information on the data. "you can specify" can be quite confusing when you are only there to look for info.

**Comment by marliekeverweij** [comment]
Thanks for your quick replies! I agree with Michiel that it's now confusing. The user could think that s/he could do something, but that's not possible. I am going to change the texts :)
