### ISSUE TITLE
Remove "Log in" button

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#271]
We currently have a "Log in" button. Users can create an account and with that account they can clone a dataset and adjust that cloned dataset.

This cloning functionality is not something we want to support for users (https://github.com/quintel/etlocal/issues/272). Therefore, @michieldenhaan and I would propose to remove the "Log in" button as it adds no additional value for users!

Quintellers do have to log in to adjust the dataset, but we could use the link: https://beta-local.energytransitionmodel.com/users/sign_in

![Screenshot 2021-02-26 at 11 56 10](https://user-images.githubusercontent.com/32833996/109291740-9f81ac80-7829-11eb-976d-e040e6569c03.png)

**Comment by noracato** [comment]
I'm not so sure about this one.

You would need to keep track of the login link between the people that want to update datasets. Which I think will become irritating in the future.
Moreover the login button is not in an annoying spot, nor is it a feature people don't not know how to handle; it's exactly where/what people would think it should be. 
Sure, when someone creates an account, there's nothing special they can do with it (for now). But I don't see the harm in that. I think just disabling the cloning button solves most of the problem.
