### ISSUE TITLE
Hide "clone dataset" button

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#272]
At the moment it is possible to clone an existing dataset and adjust that dataset. The goal of dataset-cloning is to give users the possibility to create their own dataset. Also cloning makes it possible for ourselves to create different versions of one region.

However, this feature is barely used. Therefore, we want to propose to remove it. 
Reasons:

- we do not see it happen that users will create their own dataset in the near future
- we can ask ourselves if we find it desirable to have different versions of one region 
- the cloning functionality is not functioning properly: for example the cloned dataset is always called "Quintel" so you cannot distinguish which dataset is which, you cannot remove a cloned dataset, etc.

![Screenshot 2021-02-26 at 12 18 07](https://user-images.githubusercontent.com/32833996/109293870-b249b080-782c-11eb-92d5-c854675ba930.png)

What do you think? @quintel/core

**Comment by redekok** [comment]
I have actually recently used this feature to create a dataset for Haven-Stad, an area that hadn't been defined yet. However, I guess it's would be cleaner to add this area shape to the layer. Thus, I guess I'm fine with removing it. One remaining question: will the cloned datasets (such as the Haven-Stad dataset) still be available in the database after removing it? :-)

**Comment by noracato** [comment]
We can also just hide the button to start with. If people really miss the feature we can easily bring it back, and adjust it to our (new) needs. If it remain un-missed, we can remove it during the next milestone.

**Comment by marliekeverweij** [comment]
Yes I like that idea!

**Comment by jorisberkhout** [comment]
I agree with hiding the button for now!
