### ISSUE TITLE
CO2 sheet in description should point to the correct region

### ISSUE THREAD

**Issue by noracato** [quintel/etlocal#285]
In the Emissions tab, we link to the CO2 footprint factsheet for the NL region regardless of the dataset that you are viewing. We should adjust this to point to the CO2 sheet of the currently viewed dataset.

<img width="670" alt="Screenshot 2021-03-22 at 11 40 33" src="https://user-images.githubusercontent.com/14875123/111977929-a091bb00-8b03-11eb-9203-33768b883e3c.png">

**Comment by michieldenhaan** [comment]
This will soon be outdated with the upcoming green house gas update. Think it's not worth to spend time on for now
