### ISSUE TITLE
Remove the 'open scenario in ETM' button

### ISSUE THREAD

**Issue by noracato** [quintel/etlocal#286]
When you click a dataset on the map, a bubble opens with two options: view the dataset or open a scenario in the ETM. This last button has been disabled forever. Is it time to remove it?

@marliekeverweij @michieldenhaan @AlexanderWirtz

**Comment by AlexanderWirtz** [comment]
I vote yes, until such a time when we can actually enable it.

**Comment by marliekeverweij** [comment]
I vote yes too!

**Comment by noracato** [comment]
We can easily make a valid link to a new ETM scenario, that's no problem. The only issue is that we can only do that when we have an end-year for the scenario. So _we_ would have to pick a static end-year for all scenarios created through this button.

Maybe my question here was more: why did we disable the button? And why was it there in the first place?

**Comment by michieldenhaan** [comment]
I prefer to remove it as well (maybe the whole pop-up, i.e. clicking on a region should immediately open the dataset). The original idea was that users could create a dataset in ETLocal and then open it in the ETM to inspect it, but I think we shelved that idea.

**Comment by noracato** [comment]
Ah, no than it would not in the least be straightforward to start a scenario (from a user created dataset I mean).

The only thing about the tiny popup that I like, is that you can verify that you clicked the right dataset. For instance when you want to open the province of Friesland and not the RES regio Friesland. They have about the same shape, but are accessible on a different zoom-level.

**Comment by marliekeverweij** [comment]
@noracato could you remove the 'open scenario in ETM' button? I think it's confusing for users to see the button, especially now that we want to attract more attention to the ETM Dataset Manager :)
