### ISSUE TITLE
Clicking on the municipalities is quite buggy in Firefox 86.0.1

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#287]
Browser: Firefox 86.0.1
OS: macOS big sur

See video:

https://user-images.githubusercontent.com/2676542/111979654-9d97ca00-8b05-11eb-9243-76916ccd4904.mov

EtLocal looks pretty great 👍 . I was clicking around a bit and noticed this glitchy bug in Firefox. It might actually be Firefox exclusive but I'm not sure. I'm not sure what's going on but this is probably Mapbox's doing.

**Comment by marliekeverweij** [comment]
Thanks @grdw! Nice that you're checking out the updated Dataset Manager. It probably still feels like your baby! 👶🏼

**Comment by grdw** [comment]
> It probably still feels like your baby! 👶🏼

I saw it in its diapers and everything; taking its first steps. Also; I sometimes still see some activity flying by on github, so I couldn't resist checking it out for a minute or so.
