### ISSUE TITLE
Area hierarchy

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etlocal#29]
If we want to use ETlocal to create an ETM for every neighbourhood in the Netherlands, the list will become way too long. Also, not every neighbourhood has a unique name (for instance there is also a Biezen in Nijmegen, Alphen ad Rijn and Amersfoort, besides the one in Dongen we all know and love). Therefore we should add some sort of menu structure. 

CBS uses four levels, which for us would probably work as well: Province, municipality, district and neighbourhood. 

There is a code system, the provinces are coded PV20 to PV31, the municipalities have a GM and then 4 digits, the districts start with WK, then the 4 digits of the municipality and a 2 digit district code, and the neighbourhoods have BU in front, then the municipality code, then the district code and then the neighbourhood. So for instance Quintel:
Province: PV27 (Noord Holland)
Municipality: GM0363 (Amsterdam)
District: WK036303 (Grachtengordel Zuid)
Neighbourhood: BU03630302 (Van Loonbuurt)

We can use the same codes for ETlocal, we can think about if we want both the districts and the neighbourhoods, or maybe just 1 of those.

**Comment by BerendSmits** [comment]
Perhaps a check should be done if all klimaatmonitor data for this hierarchy adds up, and the average usages work as weighted averages, then we can build up the provinces and the districts from the neighbourhoods.

**Comment by grdw** [comment]
See https://github.com/quintel/etsource/issues/1180

**Comment by BerendSmits** [comment]
We implemented this for etlocal, closing
