### ISSUE TITLE
Ensure that each GEO_ID has one related dataset

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#298]
Last week @michieldenhaan @noracato and I discussed about the datasets in the ETM Dataset Manager. At the moment one GEO_ID can have multiple related datasets (since we had the clone-button). For each regional dataset on ETSource we want to link to the dataset in the dataset manager. For that purpose it's undesirable to have multiple datasets for one GEO_ID, we want to have one dataset per GEO_ID. Here is the list of the cloned datasets:

- [[“Alphen aan den Rijn”, “Robot”], [“Alphen aan den Rijn”, “nora”]],
- [[“Amsterdam”, “Robot”], [“Haven-Stad”, “Roos ”]],
- [[“Texel”, “Robot”], [“Texel”, “marlieke”]],
- [[“Reitdiep”, “Dorine”], [“Reitdiep”, “Dorine”], [“Reitdiep”, “Dorine”], [“Reitdiep”, “Robot”]],
- [[“Selwerd”, “Dorine”], [“Selwerd”, “Dorine van der Vlies”], [“Selwerd”, “Dorine” [“Selwerd”, “Dorine”], [“Selwerd”, “Dorine”], [“Selwerd”, “Dorine], [“Selwerd”, “Dorine”], [“Selwerd”, “Dorine”], [“Selwerd”, “Robot”]],
-  [[“Gelderland”, “Robot”], [“Gelderland”, “Anthony”], [“Gelderland”, “Anthony”], [“Gelderland”, “marlieke”]],
- [[“Holland-Rijnland”, “Robot”], [“Holland Rijnland”, “Mart”]]

Many of the cloned datasets are not used anymore, so we could remove most of them and keep the one created by "Robot". 

However, two datasets are still used: “Haven-Stad" and "PV25_gelderland_plus" (dataset number 18517). For these datasets we have to add them to the database with a new GEO_ID as it's really a different region with different boundaries. I propose to use:
- “Haven-Stad” => GM0363_2
- Gelderland plus => PV25_2

If people have better suggestions, let me know!

After this we could tackle this issue: https://github.com/quintel/etlocal/issues/281

**Comment by michieldenhaan** [comment]
I think it's better not to use underscores in geo IDs

**Comment by noracato** [comment]
I agree with @michieldenhaan. We currently use an underscore behind the id to specify the name of the region in many places around the ETM. Adding an extra underscore like this has the possibilty to mess up some logic surrounding that. If we want to treat these areas as seperate regions, I think we should create a new ID for them, like `PV32` for Gelderland plus (highest we have right now is 31). 

We could do something similar with Haven-Stad, but I'm wondering if we should treat that region as a neighbourhood or as a municipailty. Do you have any preference as the creator @redekok?

**Comment by redekok** [comment]
Fine by me to not use underscores in geo IDs. I am a bit hesitant in using PV# for the Gelderland plus dataset and either a GM# or BU# for the Haven-Stad datasets since these are not the geographical definitions of the datasets. Gelderland plus is an extension of the province and Haven-Stad is rather a (yet not officially defined) district ("wijk") than a neighbourhood. Could we use a new prefix for those datasets? I noticed the ID of Groningen-Drenthe being RGGD01. Maybe we could do something similar for the Gelderland plus and Haven-Stad dataset? Another reason not to use the PV and BU prefix for these datasets is that we usually match these to the CBS IDs. Creating new PV# or BU# IDs might be confusing to our users?

**Comment by noracato** [comment]
Good to know! Nice idea of the new identifiers. We could introduce a new _District_ identifier like `DI` for Haven-Stad and something like a ProvincePlus `PVP` or a Department `DPT` for the GederlandPlus set?

**Comment by marliekeverweij** [comment]
Good idea to know use `GM` and `PV` for these regions.

In line with RGGD01 and RGNH01_ijmond_zuid_kennemerland etc. I propose to use `RGGLDO1` for Gelderland-plus

For Havenstad, let's do `DIAMS01` (AMS = Amsterdam). When this "wijk" will be official, then we'll have to change it anyways

**Comment by redekok** [comment]
Or maybe `RGAMS01`?

**Comment by marliekeverweij** [comment]
Yes, that's better!

**Comment by noracato** [comment]
There are now three PR's to update the area codes for ETSource, ETEngine and ETModel. If they're merged and you guys are happy, I'll move all the recent changes to ETLocal pro as well.
