### ISSUE TITLE
Migrate from Paperclip to ActiveStorage

### ISSUE THREAD

**Issue by antw** [quintel/etlocal#299]
[Paperclip is deprecated](https://github.com/thoughtbot/paperclip#deprecated) and Thoughtbot recommend switching to ActiveStorage.

Switching has become more pressing now since mimemagic – on which Paperclip depends – has yanked older versions of the Gem and [now requires extra dependencies to be manually installed](https://github.com/mimemagicrb/mimemagic#dependencies). ActiveStorage does not depend on mimemagic.

Swapping out Paperclip in code should be easy, as its only used in one place: the `Source` model, which allows attaching a file to a `Commit`. However we'll also have to migrate the DB and potentially move files.

* [Migrating from Paperclip to ActiveStorage](https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md)

Alternatively, if we want to drop support for attaching files to commits we can remove the Paperclip dependency entirely, along with the 21 files currently stored. No files have been uploaded since mid-2019, so it seems the feature may not be very widely used. @michieldenhaan: Do you have an opinion on this?

**Comment by michieldenhaan** [comment]
Discussed this briefly with @marliekeverweij and we're both happy with removing the dependency!
