### ISSUE TITLE
Add interface elements voor emission factors of energy carriers

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#303]
We want to make it possible to easily set emission factors for energy carriers per dataset. Therefore, we want to add the emission factors of the most important energy carriers to our dataset manager. @antw has already implemented the technical support for this :) 

I would propose to add the following carriers:

- Coal
- Crude oil
- Diesel
- Gasoline
- Heavy fuel oil
- Imported electricity
- Imported heat
- Imported hydrogen
- Kerosene
- Lignite
- Lng
- Lpg
- Natural gas
- Non biogenic waste

And I would propose this location:
![Screenshot 2021-05-04 at 09 57 18](https://user-images.githubusercontent.com/32833996/116975177-8250da80-acbf-11eb-94f9-e851340eb59b.png)

It will also be possible to make energy carrier costs and the potential CO2 emissions for biomass products dataset-dependent. For now I would like to focus on the emission factors. 

Let me know when you have any feedback @michieldenhaan @AlexanderWirtz and more Quintellers :) 

Here's how we should implement is (copying Anthony's text here):

> ETLocal is capable of creating a carrier.csv file for datasets when values differ from those in the parent dataset. If ETLocal has no custom values, or the values are identical to those in the parent dataset, a symlink to the original is created instead.
> 
> These values can be set in ETLocal using an interface element with a key such as:
> 
> `file_carrier_${row_key}_${col_key}`
> 
> For example:
> 
> `file_carrier_coal_co2_conversion_per_mj`
> 
> The feature is flexible enough that we could use this to customise other CSV files.

Steps to take:

1. - [x] Add interface elements to ETLocal
2. - [ ] Add values for emission factors to all datasets in the dataset manager through a migration

**Comment by michieldenhaan** [comment]
Sounds good! If possible it would be nice to wait until the CO2 project is merged as this includes updates to the emissions section (merge = somewhere this week).

The 'new' emissions section is becoming quite lengthy, so we could also consider adding a separate 'emission factors' submenu item.

https://user-images.githubusercontent.com/32056448/116986766-7d475780-acce-11eb-86f2-82a89c64b846.mp4

**Comment by marliekeverweij** [comment]
Allright! Could you let me know when it is merged?

> The 'new' emissions section is becoming quite lengthy, so we could also consider adding a separate 'emission factors' submenu item.

Good idea
