### ISSUE TITLE
Improve dataset export procedure

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#306]
At the moment we use the dataset ID to export datasets to ETSource. For this we need[ this overview list ](https://github.com/quintel/etlocal/wiki/Overview:-datasets-and-dataset-IDs)with all ETLocal datasets incl. mapping of geo-id and dataset ids. This list is manually updated and this is very time-consuming. 

@noracato also implemented the feature that we could easily see the dataset ID when hoovering over the dataset name in ETLocal:
![Screenshot 2021-05-14 at 17 06 13](https://user-images.githubusercontent.com/32833996/118290414-b35ab780-b4d6-11eb-8c20-6cd50affc6e9.png)

**Idea**
However I think the easiest way would be to use the GEO_ID for exporting instead of the dataset IDs. In our current workflow we always add a geo_id to the dataset name. What do you think? @michieldenhaan @noracato @antw 

We could also choose to automatically generate the overview list with a rake task based on the datasets that are ETSource.

**Question**
Are there more things we would like to have improved? I could also imagine it to be nice to have a way to export all ETLocal datasets at once, or all Dutch datasets.....

**Comment by antw** [comment]
> However I think the easiest way would be to use the GEO_ID for exporting instead of the dataset IDs.

I agree. Numeric IDs should only ever be a last resort, in part for the reasons you suggested, but also because they are not consistent. A migration that adds a new dataset is not guaranteed to get the same numeric ID. The flip side is that `geo_id` must be unique; we can't have two datasets with the same `geo_id`.

I don't think this is an issue anymore, but it might have been in the past when we allowed people to create their own versions of a dataset. Could this become a problem again in the future?

**Comment by marliekeverweij** [comment]
> I don't think this is an issue anymore, but it might have been in the past when we allowed people to create their own versions of a dataset. Could this become a problem again in the future?

Good point. As long as we do not allow users to create different version of the same regional datasets, this is not a problem anymore.

@noracato @antw could you adjust this?

**Comment by marliekeverweij** [comment]
It would be great if this could be adjusted. That would save us time (not having to look for numeric IDs in this list: https://github.com/quintel/etlocal/wiki/Overview:-datasets-and-dataset-IDs). Could you maybe add it to your next sprint?

**Comment by marliekeverweij** [comment]
@noracato you once told me that this is an easy and quick fix. Could you make this happen for the entso-project on the `steel`-branch?

**Comment by noracato** [comment]
Sure!
