### ISSUE TITLE
Commit messages: which language do we want to use?

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#309]
As the dataset manager has been mostly used for Dutch datasets, most commit messages are in Dutch now. Now that we are thinking of adding more international regions, we should reconsider the language of the commit messages.

I think we have two options:
1. Write the commit messages in the Dutch for Dutch and Belgian regions and in English for non-Dutch speaking regions
2. Always write a Dutch and English commit message for each commit and the shown language depends on the language selection.

I think option 1 will suffice for now. Option 2 is a lot more work: always having to write two messages for each commit.

What do you think @michieldenhaan @antw @noracato ?

![Screenshot 2021-05-20 at 11 19 49](https://user-images.githubusercontent.com/32833996/118953633-4bd0bc00-b95d-11eb-9193-9a01099499f1.png)

**Comment by antw** [comment]
I'm biased, but English would be my choice when wanting to be useable by the largest possible audience. In this case, It's not a strong opinion though. 😉

**Comment by mabijkerk** [comment]
I will put this question forward to the team. My preference would be to use English.

**Comment by mabijkerk** [comment]
The conclusion is that the preferred language is English. However, if preferred, it is possible to use the local language for local datasets.
