### ISSUE TITLE
Buildings analyzes

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#31]
Buildings are analyzed with their useful demands only (i.e. building nodes at the left side of the graph).

Aanalyzing takes a single input which is the amount of buildings in m<sup>2</sup> of a certain area.   That is converted to a number of buildings.

That number of buildings is compared to the original scaled number of buildings and returns a factor. That factor is multiplied to all the useful demands on the left side of the screen and set through an initializer input.

**Comment by BerendSmits** [comment]
For the average area per building, from the buildings insulation analsysis (/Dropbox (Quintel)/Quintel/Projects/2013_projects/201307_Insulation.xls):


![screen shot 2017-03-15 at 14 33 05](https://cloud.githubusercontent.com/assets/24872776/23950821/928f6b62-098c-11e7-9a3b-5d7c2148c9ef.png)

**Comment by grdw** [comment]
1223 m<sup>2</sup> it is 👍 thanks

**Comment by BerendSmits** [comment]
When I run the rake etsource export the first time, this works nicely, but the second time all the UD's are set to 0, do you know why this is @grdw?

**Comment by grdw** [comment]
Yes 👍 but I already fixed that with: https://github.com/quintel/etlocal/commit/50c285b8ad58a3aad9c7186e5f5fd18431940083#diff-fa5f1f75aaa42ea28069e8003256f4d5
