### ISSUE TITLE
Number precision not observed when logged in

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#313]
When not logged in 4 decimal places are shown:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/32056448/119979928-dc417900-bfbb-11eb-802e-b62b75e9b169.png">

Logged in only two:
![image](https://user-images.githubusercontent.com/32056448/119979950-e5324a80-bfbb-11eb-8ccb-65214875d3a9.png)

**Comment by antw** [comment]
I took care of this, since it was I that added support for custom precision and neglected to do so for the form elements.
