### ISSUE TITLE
Creating datasets for each neighborhood of nl

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#33]

**Comment by BerendSmits** [comment]
@grdw where would you like the .csv with all the district data? etdataset?

**Comment by grdw** [comment]
> where would you like the .csv with all the district data? etdataset?

For the sake of keeping that file in git, yes. I'll still need to copy/paste it on my local machine to create all the datasets from ETLocal and modify the existing creation script and what not 👍

**Comment by grdw** [comment]
Closing due to obvious size constraints.
