### ISSUE TITLE
District heating

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etlocal#34]
If we are going to add all neighbourhoods of the Netherland, we're going to find a few with district heating. So far, we have not accounted for this. The klimaatmonitor data gives us a percentage of houses with district heating, and an average gas usage per HH (including the ones with district heating). 

I would suggest, for the neighbourhoods where district heating's market share is lower than, say, 70%, we use the gas usage of their neighbours to estimate the hot water and space heating demand. This means we would put the district heating final demand at (average_gas_use/(100-%district_heating))*%district heating (converted from m3 gas to GJ). 

For the cases where the district heating percentage is higher than 70%, we cannot rely on the gas use (it will no longer be representative of the area, or in the case of 100% district heating, it will just not be there). Then, I would propose to let the district heating UD be determined by the municipality average. 

This means two extra entries in our ETlocal interface (district heating percentage and district heating average heat delivered), and a few changes to our analysis. @ChaelKruip and @dennisschoenmakers do you agree with these changes? 

@grdw do you want to discuss this or should I process it into https://github.com/quintel/etlocal/issues/21?

**Comment by ChaelKruip** [comment]
> do you agree with these changes?

👍

**Comment by grdw** [comment]
> @grdw do you want to discuss this or should I process it into #21?

I'd like to discuss it in this ticket and not include it in #21, because I'm not notified if anything changes to that ticket. 👍

**Comment by BerendSmits** [comment]
This is continued in https://github.com/quintel/etlocal/issues/54
