### ISSUE TITLE
Drawing the netherlands with all it's provinces - municipalities - neighborhoods

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#35]
*Inspiration:*

- http://wikimapia.org/#lang=en&lat=52.393830&lon=4.665070&z=12&m=b
- http://www.energieinbeeld.nl/inloggen/
- http://www.gadm.org/country (only as source for the regions)

--

I think that the shapes should become visible/less visible depending on the zoom level of the chart. A bit like the wikimapia link. 

So if you see the full Netherlands:

![screen shot 2017-03-16 at 11 29 03](https://cloud.githubusercontent.com/assets/2676542/23992085/f5d6259e-0a3b-11e7-8815-e591763606fd.png)

Only the provinces will be selectable. When you zoom in, the area will be divided in municipalities, when you zoom in further you'll see the neighborhoods. 

I'm trying to find a source for these shapes/polygons/svg's/kmz's in order not to draw them myself. The gadm link in the inspiration section looks promising.

**Comment by BerendSmits** [comment]
CBS has shape files for the regions: https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/geografische%20data/wijk-en-buurtkaart-2015, I'm not sure if these work with google maps though..

**Comment by grdw** [comment]
Thanks! 👍 Hooray for formatting. Google only supports KML layers :man_shrugging: luckily there are some conversion methods for it 😆 I'll try to see what I can make of it. Thanks anyways.

**Comment by BerendSmits** [comment]
Besides looking for your area on the map, I could imagine people just want to search for it, would it be possible to add a search box @grdw?

**Comment by grdw** [comment]
> Besides looking for your area on the map, I could imagine people just want to search for it, would it be possible to add a search box @grdw?

It's probably possible, sure.
