### ISSUE TITLE
Proposal: we should stop maintaining two branches and only keep one

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#352]
I just had a discussion with @antw about our `production` and `master` branch on ETLocal. We created these to branches with the idea:
- That software developments go to `master` first for testing and then to `production`
- That for data-related updates (adding and updating datasets) we use `production`, because these changes will be reflected in our production environment directly. Users would like to see the exact sources that have been used for a dataset directly in our production environment without delay (on beta first, then deploying it to pro).

In practice this doesn't work.

Anthony: "The problem, I think, is that we end up with the two branches (and servers) becoming out-of-sync. Code gets run on production which has never run on beta, and beta ends up as a Frankenstein's monster where it has some of the commits from production, but is missing others."

Therefore we think it is best to do the following:

1. delete master
2. rename production to master
3. deploy both beta and pro using the new master branch

Anthony: "It means we don't have a way to test changes before sending them to production, but at least then we don't end up with this weird beta that we have today."

What do you think @noracato @Charlottevm @michieldenhaan and anybody else from @quintel/core that wants to chip in

**Comment by noracato** [comment]
I fully agree with getting rid of the master branch as it is now, I don't think anybody would miss it in its current status. What would be the reason then to keep the two servers running, if they're based on the same branch? Just curious.

**Comment by MartLubben** [comment]
I do know one reason (not sure if that is a good one):
For the Elia project we (Michiel and I) decided to add the Elia datasets to the beta server of ETLocal, because they are partial datasets (only about the built environment). For this reason we did not want them on the live server, but we did want Elia to see the detailed input of their datasets

**Comment by noracato** [comment]
Mostly Marlieke and Michiel wanted to get rid of it if I remember correctly. I don't have a strong preference, but I think it could be useful for the dataset project to keep the beta version around for testing.
