### ISSUE TITLE
It should be possible to give start value for insulation per housing type in three digits in the Dataset Manager

### ISSUE THREAD

**Issue by MartLubben** [quintel/etlocal#366]
The dataset manager rounds the input for insulation start values housing types to two digits, it should be at least three digits, as showed in the front end (see picture 1). I had to manually change it to one digit behind the '.' , see: https://github.com/quintel/etsource/pull/2619 

Next to this the Dataset Manager shows '0.35' when clicking the '35' %, when you save it (without changing the number) the dataset manager stores it as 0% (rounded and divided by 100). I hope this is described clear enough, but feel free to contact me. 

![image](https://user-images.githubusercontent.com/33415156/152534322-3fad9b7f-6ace-4389-83c2-e7279fa4da81.png)

![image](https://user-images.githubusercontent.com/33415156/152534534-432ebffa-ec3e-404c-8b77-b66f64695c29.png)

**Comment by mabijkerk** [comment]
This is no longer relevant since the recent changes in heat modelling.
