### ISSUE TITLE
Missing locales in datasets

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etlocal#370]
In the Dataset Manager there seem to be some fields that don't have locales. Instead, these fields will display the input statement with each first letter capitalized. It can most clearly be seen when the Dutch locales is selected in the front-end, because the input statement are in English:

<img width="714" alt="Screenshot 2022-02-14 at 16 40 54" src="https://user-images.githubusercontent.com/67338510/153895981-f2a0579a-36fe-474f-96d2-c9647a2dee6a.png">

<img width="714" alt="Screenshot 2022-02-14 at 16 40 31" src="https://user-images.githubusercontent.com/67338510/153895907-dc96ce01-4954-406c-9500-b51532b3a606.png">

<img width="704" alt="Screenshot 2022-03-10 at 10 30 55" src="https://user-images.githubusercontent.com/67338510/157632623-dabbb8a1-3779-46a7-8ba1-e73b03be307c.png">

<img width="655" alt="Screenshot 2022-03-23 at 14 50 34" src="https://user-images.githubusercontent.com/67338510/159714960-895a0ac2-3830-40e4-8701-8c1c683a00a2.png">

<img width="640" alt="Screenshot 2022-03-23 at 14 50 46" src="https://user-images.githubusercontent.com/67338510/159714997-5829b465-668a-4c0d-9846-731f1498d3b9.png">

Notifying @marliekeverweij and @Charlottevm

**Comment by marliekeverweij** [comment]
More translations missing
<img width="783" alt="Screenshot 2022-04-01 at 10 02 47" src="https://user-images.githubusercontent.com/32833996/161221566-c4aa1c98-54d5-4f21-bcfb-932ce5f52e57.png">
