### ISSUE TITLE
Adding a geocoding search API for Mapbox

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#39]
Mapbox GL has a method called `flyTo` where you can specify to which area in the chart it should move to. It might be useful to use the [Google Maps geoocoding search API](https://developers.google.com/maps/documentation/geocoding/start). Mapbox also provides a [similar API](https://www.mapbox.com/geocoding/) but that one is not entirely free (Make up to 600 requests per minute).

**Comment by grdw** [comment]
@ChaelKruip do you think 600 requests per minute is something we're ever going to exceed? I personally would think not 🤔 it's about 10 requests per second. Google Maps Geocoding API however is also [not free](https://developers.google.com/maps/documentation/geocoding/usage-limits).

**Comment by grdw** [comment]
[Openstreetmaps](http://wiki.openstreetmap.org/wiki/Nominatim) geocoding API is free though 😄

**Comment by ChaelKruip** [comment]
> @ChaelKruip do you think 600 requests per minute is something we're ever going to exceed?

If we do, I'm willing to pay for it 😆

**Comment by grdw** [comment]
```bash
curl "nominatim.openstreetmap.org/search?format=json&q='1017DT, Amsterdam'"
```

returns

```json
[{"place_id":"160652536","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","boundingbox":["52.363712127027","52.363812127027","4.8950191783784","4.8951191783784"],"lat":"52.363762127027","lon":"4.89506917837838","display_name":"Amsterdam, Centrum, Amsterdam, MRA, Stadsregio Amsterdam, Noord-Holland, Nederland, 1017DT, Nederland","class":"place","type":"postcode","importance":0.335}]
```

**Comment by grdw** [comment]
With the bounding box attribute we receive from openstreetmap we can easily do a:

```javascript
map.fitBounds([[
        boundingbox[0],
        boundingbox[2]
    ], [
        boundingbox[1]
        boundingbox[3]
    ]]);
```

And it will fit to the correct area 👍
