### ISSUE TITLE
Post-calculation validations should not fail

### ISSUE THREAD

**Issue by MartLubben** [quintel/etlocal#390]
While changing the `RES07` dataset (RES Goeree-Overflakkee) this error occurred. I am not sure what it is and why it happened. I changed the 514 TJ of diesel in ships fuel to 0 TJ. When doing the samen change for the `GM1924` dataset, no issue occurred. 

![image](https://user-images.githubusercontent.com/33415156/166201296-7fd17c9e-24cd-4d56-b99e-bc2c0c741eb1.png)

**Comment by marliekeverweij** [comment]
This has to do with a rounding error in the municipal datasets procedure. @Charlottevm is aware of this :)

**Comment by mabijkerk** [comment]
@Charlottevm can this be closed?
