### ISSUE TITLE
Missing hydrogen sliders

### ISSUE THREAD

**Issue by antw** [quintel/etlocal#401]
There are two sliders currently missing for recently added hydrogen nodes and edges:

- **bunkers_final_demand_hydrogen_demand**

  Added in [quintel/etsource@c729b40](https://github.com/quintel/etsource/commit/c729b409604cf1cd64930eca27e097f3d018affd#diff-f0929f2cb9661b5da1da11ec6a348d1d48c4106d1d884fe5d1865923a87f653aR6)

- **buildings_final_demand_for_space_heating_electricity_buildings_space_heater_hybrid_hydrogen_heatpump_air_water_electricity_parent_share**

  Added in [quintel/etsource@b6db9ef](https://github.com/quintel/etsource/commit/b6db9ef7de5353d9e5cab606025d4f71f3ef62c9#diff-d8bce7b5b9993cf094fbcbd446ce6ee6133f2e6e964d290770713b00e8009ce3R4)

Missing inputs means ETLocal will not deploy. I have temporarily omitted these two sliders from the tests, but it would be good to get them added as soon as possible.

**Comment by mabijkerk** [comment]
I understood from @marliekeverweij that we didn't have to add them to ETLocal as sliders, as they are 0 in all base years. Is this not the case @antw? For example for international navigation LNG is also not present in ETLocal. The same goes for bio-kerosene for international aviation and for hybrid hydrogen heating for households as a heating application.

**Comment by antw** [comment]
@mabijkerk As far as I can tell, LNG, kerosene, etc, don't have a `graph_method` attribute. This is why no slider is needed in ETLocal. I'm pretty certain that if a node or edge has a `graph_method` attribute a slider _must_ be present in ETSource.

If this is not something intended to be edited by users of ETLocal, and is not set by ETLocal some other way (for example, through an ETNSO energy balance) you can probably remove the attribute from the node file.

**Comment by mabijkerk** [comment]
You're absolutely right, thanks for taking a sharp look. I'll change it on ETSource right away.
