### ISSUE TITLE
No version history appears for co2 of international aviation

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etlocal#403]
For some reason there is no version history for emissions of international aviation/shipping, any idea why @noracato? It does not happen in other datasets.

<img width="707" alt="afbeelding" src="https://user-images.githubusercontent.com/74194356/179985668-c3e63ee6-6cae-488a-a292-db8b1c979235.png">

**Comment by marliekeverweij** [comment]
Which dataset is this? @Charlottevm

**Comment by marliekeverweij** [comment]
I think this has to do with the connection between ETSource & ETLocal that @noracato & I found out a year ago. When no value is filled in / migrated, then it is possible that ETLocal retrieves its value directly from the dataset in ETSource (magic ✨)

For this it's necessary that the ETLocal key exactly matches the key used in the "area-file" in the dataset: the file ending with `.derived`
