### ISSUE TITLE
Are provinces going to have their own datasets?

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#41]
If so, it would be nice if they would live as a separate entity inside of the [datasets.csv](https://github.com/quintel/etdataset/blob/master/supporting_data/nl_datasets.csv) file.

**Comment by ChaelKruip** [comment]
I think the answer is "YES"!

**Comment by BerendSmits** [comment]
> I think the answer is "YES"!

YES!

**Comment by BerendSmits** [comment]
I don't feel great about treating them the exact same way as municipalities though, completely ignoring industry and agriculture becomes rather odd. Perhaps we can leave scaled values be for these sectors in the analysis @grdw?

**Comment by ChaelKruip** [comment]
> Perhaps we can leave scaled values be for these sectors in the analysis @grdw?

That would make sense. Good point!
