### ISSUE TITLE
Add support for world data sources

### ISSUE THREAD

**Issue by antw** [quintel/etlocal#412]
In the last year we added support for `entso` data sources. We'd now like to add support for an `iea` data source.

@Charlottevm Can you add any relevant information here, such as if you think there is anything that might make this difficult, differences between the IEA and ENTSO sources, etc? My assumption is that the IEA data will be a CSV in a different format to the ENTSO data?

**Comment by Charlottevm** [comment]
I just scheduled a meeting with @mabijkerk coming monday as he has researched the difference between Eurostat (entso) and IEA data and knows the answer to this question. I will let you know afterwards!

**Comment by Charlottevm** [comment]
It turns out we actually want to keep the one key and change the script so no action needed for now. We will have to change the name from entso to something else as it now includes both eurostat and iea data. Any suggestions @mabijkerk @marliekeverweij ?

**Comment by mabijkerk** [comment]
How about `energy_balance`?

**Comment by antw** [comment]
I can change the key from `entso` to `energy_balance`. Just to confirm, the CSV files stored in ETLocal will have the same structure regardless of whether they came from Eurostat or the IEA?

**Comment by mabijkerk** [comment]
The objective currently indeed is to produce with the world format energy balance a format that aligns with the Eurostat format on all the **relevant points**.

There may be some rows that Eurostat has that the world format doesn't have, or vice versa, but if we don't use these rows anyway in ETLocal it doesn't make sense to convert them. Generally speaking this means that for our purposes the structure will be the same.
