### ISSUE TITLE
Add documentation structure for hard-coded values

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etlocal#417]
The power plant efficiencies interface element contains hard-coded values, which act as fall-back efficiencies:
```ruby
      - key: input_energy_power_ultra_supercritical_coal_electricity_output_conversion
        unit: '%'
        entso: |
          IF(EB("Coal pulverized", "Coal") > 0.0,
          -> {EB("Coal pulverized", "Electricity") / EB("Coal pulverized", "Coal") * 100},
          -> {46.0})
      - key: input_energy_power_ultra_supercritical_ccs_coal_electricity_output_conversion
        unit: '%'
        entso: 36.1
```

These fall-back values seem to be retrieved from the `nl2015` dataset, but without providing any documentation. This makes it very difficult for users to trace the source of specific efficiencies. I propose to have a broad discussion about this issue that includes:

- Can we add documentation for these hardcoded values?
- Can we prevent having hard-coded values in the interface elements all-together?
- Should we update to the `nl2019` values?

**Comment by Charlottevm** [comment]
Another fall-back: if a country provides its own efficiencies we are now not able to change these as they are hard-coded.

**Proposal:** remove entso links for these interface elements and add these efficiencies in a migration.
