### ISSUE TITLE
Missing municipalities

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#43]
![screen shot 2017-03-31 at 13 25 54](https://cloud.githubusercontent.com/assets/2676542/24548454/984ed930-1615-11e7-84eb-f2f8ad5022c6.png)

As this map clearly shows - I miss 4 municipalities. I need to expand them in the nl.csv but I don't know how to fetch the default data for it (I'll update the CSV in ETDataset).

**Comment by BerendSmits** [comment]
I think this is no longer relevant right @grdw ? Can we close this?

**Comment by grdw** [comment]
This is actually still an issue only less visibly so. There still should be a 'how to deal with missing municipalities / regions' discussion. So I'll keep this open.
