### ISSUE TITLE
The static data (Shapefiles) for all the maplayers where should that live?

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#44]
It's now only on my Mac which seems like a single point of failure. Considering the amount of edits in QGis / mapshapper etc. it might be worthwhile to put them in a git repository? 

Do you have a specific preference @ChaelKruip ?

**Comment by grdw** [comment]
One thing to keep in mind: the current size is 407MB (of all original layers, center corrected layers, compressed layers combined). This is for `nl` only. If we're going to support for example other countries git might become less useful.

**Comment by ChaelKruip** [comment]
I think this will be NL for the time being. Git is a good option for now IMO.

**Comment by grdw** [comment]
Closing: https://github.com/quintel/etlayers
