### ISSUE TITLE
Add interface elements for insulation maximum values

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etlocal#449]
The current max values for the insulation sliders in households & buildings are the same for all datasets. However, these values match with the Dutch energy labels and are not standard internationally. Therefore, it should be possible to alter these values of other datasets, like Northern-Ireland: they have higher max values!

**Comment by mabijkerk** [comment]
@marliekeverweij I also seem to recall a discussion between us, where we thought about removing the min/max as area attributes and just set all max to 75%. Where do you stand on this?

**Comment by marliekeverweij** [comment]
This is also fine for me, that cleans up the area-file (a little 😉). I have no idea if these values differ between countries and if so, how they differ. I also think it's hard for users to come with a value for this max value. So I would say: LET'S DO IT!

**Comment by marliekeverweij** [comment]
Closing this issue, as there was already [an issue about this](https://github.com/quintel/etsource/issues/2815). Oops!
