### ISSUE TITLE
Remove static demands for transport

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#46]
As defined [here](https://github.com/quintel/etlocal/blob/master/config/assumptions.yml#L9)

**Comment by grdw** [comment]
Related: https://github.com/quintel/etsource/pull/1254

**Comment by DorinevanderVlies** [comment]
@antw can I close this issue as it is overwritten by [ETSource commit 1283](https://github.com/quintel/etsource/pull/1283/commits)
