### ISSUE TITLE
Update dataset_amalgamator

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etlocal#460]
The `dataset_amalgamator` branch seems not to function...
Marlieke has updated some of the keys but there might be other keys missing. 
Could you have a look what is wrong @redekok and share your expert opinion? You can use whatever region as test case.
For now the objective is to get it working again & have a list of etlocal-keys that need to be updated (if this is the case)

**Comment by redekok** [comment]
@Charlottevm let's discuss these points when you're back! 

- [ ] Review adjusted combination methods full load hours energy production
- [ ] Review adjusted combination methods industry residual heat
- [ ] Not all datasets have a value for `energy_distribution_network_gas_loss_demand`
