### ISSUE TITLE
Remove static number of attributes

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#47]
As described [here](https://github.com/quintel/etlocal/blob/master/config/assumptions.yml#L128-L132).

**Comment by grdw** [comment]
As explained by @BerendSmits yesterday the following things are connected:

[`number_of_energy_power_*`](https://github.com/quintel/etlocal/blob/master/config/assumptions.yml#L123-L126)

and

[`number_of_energy_chp_*`](https://github.com/quintel/etlocal/blob/master/config/assumptions.yml#L183-L186)

The CHP are 0'd because this has to do with the fact that a chp is combined heat and power but usually assumed not to be present in district or a neighborhood (would this assumption also apply for a municipality or province?).

--

To determine the `number_of_energy_power_*` the following needs to be done:

Per `energy_power_*`:

1. Fetch the current amount of `energy_power_*` present in the graph. 
2. Fetch the current amount of `energy_chp_*` present in the graph. 
3. Convert the `energy_chp_*` to `energy_power_*` through the `electricity_output_capacity` of the `energy_chp_*`.

Example: if a chp produces 100MW and you have 10 of them. You'd have 1GW of energy. If the `capacity` of a single `energy_power_*` is 500MW you'd need 2 of them to make up for the missing `energy_chp_*` nodes.

@BerendSmits am I explaining this correctly? 😅

**Comment by BerendSmits** [comment]
Solution is sketched in the analyses drawing @grdw made: https://3.basecamp.com/3797409/buckets/4290417/uploads/623358777. Closing

**Comment by ChaelKruip** [comment]
I think this should be re-openend as the solution might not be obvious and is not yet in place.

**Comment by grdw** [comment]
Is no longer an issue with the [`transfomer`](https://github.com/quintel/transformer) gem changes.
