### ISSUE TITLE
Rename interface elements for all datasets due to heat improvements modelling changes 

### ISSUE THREAD

**Issue by redekok** [quintel/etlocal#484]
Due to the heat improvements modelling project a lot of dataset keys (or interface elements) have been renamed. For instance, `energy_heat_burner_coal` has been renamed to `energy_heat_burner_ht_coal`. Also, new keys have been added (e.g. `energy_heat_burner_mt_coal`) but those are out of scope of this issue. 

On the [`heat-2023`](https://github.com/quintel/etlocal/tree/heat-2023) branch these interface elements have been renamed yet, e.g. see [here](https://github.com/quintel/etlocal/blob/heat-2023/config/interface_elements/energy/energy_heat_production.yml#L27). 

For all new keys (so not the ones that should be renamed but the entirely **new** ones, such as `energy_heat_burner_mt_coal` in the example above) I have created a [migration](https://github.com/quintel/etlocal/blob/c1753f13f084aae2f9e656d402b825c393b1b5f7/db/migrate/20230825075654_heat_improvements.rb). The `data.csv` file in the corresponding folder contains all new interface elements and their values, not the ones that are to be renamed. I did create an [overview](https://github.com/quintel/etlocal/blob/c1753f13f084aae2f9e656d402b825c393b1b5f7/db/migrate/20230825075654_heat_improvements.rb#L3-L22) in the migration script of the keys that have to be renamed.

At first, I wanted to include the rename operation in the existing migration. But on second thought it might seem like a better (and neater?) idea to create a separate migration for this. What do you think @thomas-qah? 

As for your question on Slack about the `DatasetEdits` I'm not sure whether this is the case. Perhaps @noracato can help you out here?

**Comment by thomas-qah** [comment]
As just discussed with @redekok I think creating a separate migration for the renaming of the keys is indeed a bit neater.

To rename the keys I've looked see whether this was done previously and this seemed to be the case, most recently [here](https://github.com/quintel/etlocal/blob/6bafea8fb07d7fcd847f5b93fd40ac2c3b46cd8a/db/migrate/20221104083301_rename_fertilizer_residual_heat_edge.rb). This seems to be a rather inefficient manner of renaming however. I've therefore changed this to be a bit more efficient [here](https://github.com/quintel/etlocal/blob/baa1fb16618bc3895e0880ba608ee85857df87ac/db/migrate/20230830153143_rename_interface_element_keys_heat_2023.rb).

**Comment by thomas-qah** [comment]
This issue was resolved through [this](https://github.com/quintel/etlocal/blob/heat-2023/db/migrate/20230830153143_rename_interface_element_keys_heat_2023.rb) migration.
