### ISSUE TITLE
Spaces in area names

### ISSUE THREAD

**Issue by BerendSmits** [quintel/etlocal#51]
When there is a space in the name of an area, the rake etsource:export task does not work. It gives an error saying 'dataset does not exist'. 

If you then add the geo_id to the scaled .ad file on etsource, the rake export task does seem to work, it prints a very long story and then Successfully analyzed and exported Area, but nothing is written into the .ad file on etsource.

**Comment by grdw** [comment]
I looked at @BerendSmits's laptop and it seems that the exporter can't find the edits for that specific region. I'll try to test and see if I can reproduce this myself.

**Comment by BerendSmits** [comment]
@grdw is it true that the rake export now only works when you add a geo id in the ad file?
