### ISSUE TITLE
Fix interface editing a dataset for a certain region

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#52]
![screen shot 2017-04-10 at 11 32 40](https://cloud.githubusercontent.com/assets/2676542/24855292/6d971580-1de1-11e7-981d-3b58fdd93b6f.png)

It's now really hard to tell that you can actually edit a value. Next to that, the controller in the back-end is perfectly capable of handling multiple edits with a single commit message.

---

![screen shot 2017-04-10 at 11 48 28](https://cloud.githubusercontent.com/assets/2676542/24856042/a3f2cb4a-1de3-11e7-8228-3e58735e4b39.png)

So maybe, we could turn (see screenshot) into a form.  When somebody changes a value, show the message + source bit (the view you now have on your left-hand side when you're on the edit screen).

This only leaves us with the history.

**Comment by grdw** [comment]
What do you think @ChaelKruip ?

**Comment by ChaelKruip** [comment]
> What do you think @ChaelKruip ?

I think this is a big improvement!

**Comment by grdw** [comment]
To elaborate a bit more:

![screen shot 2017-04-11 at 09 54 52](https://cloud.githubusercontent.com/assets/2676542/24898379/fdaf6c56-1e9c-11e7-8424-d1b74beccc97.png)

You would fill in all the numbers you'd want to change. Than you'd hit "Apply". 

Than you'd go to the next form:

![screen shot 2017-04-11 at 09 56 24](https://cloud.githubusercontent.com/assets/2676542/24898413/24794dc0-1e9d-11e7-9ca2-3ed49fe8a80f.png)

Where you specify the reason for your changes.
