### ISSUE TITLE
Links in citations reference old file structure

### ISSUE THREAD

**Issue by louispt1** [quintel/etlocal#559]
Some links in citations reference the old file structure, for example:
https://github.com/quintel/etlocal/blob/production/data/datasets/NL.csv

**Comment by mabijkerk** [comment]
@louispt1 could you assign a person you think this would be relevant for? Additionally, the link you specify gives a 404.

**Comment by louispt1** [comment]
Sorry - this is not a well explained issue!

What I mean is that for these links (where it says 'view energy balance'):
<img width="692" alt="image" src="https://github.com/user-attachments/assets/20d7a557-613b-4c28-ac44-ca0f5ec14f62">

Because the link structure has changed, the links now lead to a 404 as they are no longer valid - like this one: https://github.com/quintel/etlocal/blob/production/data/datasets/NL.csv. 
The same link should now be: https://github.com/quintel/etlocal/blob/production/data/datasets/energy_balance/NL_energy_balance_enriched.csv 

I am assigning this to @kndehaan because I think it is very much an extension of #557.
