### ISSUE TITLE
Adding industry to the dataset analyzes

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#59]
As specified [here](https://trello.com/c/COSAWoD8/1-5-adding-industry-to-analyses). There are three layers of adding in industry inputs. 

1. Turning it on/off
2. Specifying per sector what the final demands are etc. to determine the useful demands
3. Setting initializer inputs manually

Step 1 and 3 are easy to implement for the analyzer. The 2nd step needs a lot more context and as @BerendSmits specified might become hard todo. Especially since every province or municipality (which I think is the correct scope for industry) might have their own statistics and data. And in order to fit that into our graph in a structured way might become a rather hard task.

What I would think a nice 2nd step would be (somwhere inbetween "full jet-pilot control" and "autopilot") is if the user would be able to set initializer inputs like:

`industry_useful_demand_for_chemical_aggregated_industry`

instead of all the individual parts which are set within that input.

**Comment by ChaelKruip** [comment]
To clarify a bit: this discussion is about how subsectors of industry can be represented to the user/researcher. 

1. Exclude/include a subsector in its entirety
2. Scale the whole subsector relative to the default (e.g., 50% of the scaled default value)
3. Specify an amount of PJ for each carrier individually for a subsector

Option 2 is technically daunting and might not even be that useful: researchers would often rather say things like "20% of all steel in NL is made in my municipality" or "4 megaton of steel is made in my municipality". 
Therefore I suggest to do 1 and 3 first and think about extensions if we need them.

Including @jorisberkhout @AlexanderWirtz @DorinevanderVlies @BerendSmits

**Comment by BerendSmits** [comment]
> I suggest to do 1 and 3 first and think about extensions if we need them.

I agree this is a good place to start, this gives the researchers the "full jet-pilot control", so enough possibilities to create any dataset desired/ 

> Option 2 is technically daunting and might not even be that useful

I am not sure actually if it is that difficult. I talked it over a bit with @grdw, all the initializer inputs for the industry sector are already UPDATE_WITH_FACTOR, it would just be a matter of selecting the right one (or ones, for some sectors we need a few). And as to the matter of asking the user a percentage of the national or regional value, the scaling factor can convert one into the other. 

As for the usefulness, the emissieregistratie can tell you the emissions of an entire sector nationally, and also that of specific companies, which would give you a percentage, so I think it might be quite useful. 

This would mean however that the user is slightly blind into what energy demand he is scaling, so we need to think of an insightful way of reporting either the national or the scaled total.

**Comment by BerendSmits** [comment]
This discussion should be moved to basecamp: https://3.basecamp.com/3797409/projects/4290417. Closing it here
