### ISSUE TITLE
Initializer methods breaks - hybrid heatpumps

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#70]
I've created a dummy local dataset to test the initializer methods. When setting:
``households_final_demand_electricity:
  demand: 1000.0``
(or network_gas so you like), Refinery fails:
![hybridheatpump](https://user-images.githubusercontent.com/32056448/34865914-e0c0bc32-f77a-11e7-8f3e-a4e2f1abd29a.png)

The reason is that ``households_space_heater_hybrid_heatpump_air_water_electricity`` contains:
``input.ambient_heat = 0.631990003124024``
``input.electricity = 0.18056857232115``
``input.network_gas = 0.187441424554827``
which require that the ratio of network_gas and electricity coming into the hybrid_heatpump node has to be exactly as specified by ``input.electricity`` and ``input.network_gas``, otherwise Refinery stops. This means that we cannot set any final_demand_electricity we like, unless we tweak the shares of electricity and gas for hybrid heatpumps in such a way that the above ratio is met.

This is highly undesirable as this means that users of ETLocal making a dataset either have to do some very complicated side calculations to ensure the electricity/gas/ambient ratio is maintained, or we have to add some complicated share transformations to ETLocal that automatically give the correct ratio. In an ideal world, users should be able to set any demands and any shares they like without breaking the dataset.

@antw do you know if this input ratio requirement can be removed/softened. I.e. that Refinery simply continues calculating even though the ratio of electricity and gas coming into the hybrid heat pump is not exactly as specified in the .ad file? And can you think of any other places in the graph that aren't happy with setting some random demand and share values?

This issue has high priority as we were planning to use intializer methods to automatically generate 60 datasets for a project.
Notifying @jorisberkhout @ChaelKruip @DorinevanderVlies @grdw

**Comment by antw** [comment]
> This means that we cannot set any final_demand_electricity we like, unless we tweak the shares of electricity and gas for hybrid heatpumps in such a way that the above ratio is met.

I'm not clear on where those carrier input shares come from or how they are calculated. However, it does seem that NL is the only dataset with non-zero demand for HHPs.

It is my assumption that these shares are set based on how we expect HHPs to consume energy throughout the year (see quintel/etsource@4d7af36) and that they are not "fine-tuned" to match the final demand for electricity and gas (the above commit setting the shares of these carriers predates the existence of the 2015 dataset).

Perhaps @jorisberkhout or another modeller familiar with this part of the dataset can offer more insight?

**Comment by michieldenhaan** [comment]
As far as I understood from @DorinevanderVlies these ``input`` attributes are used when merit is off, so the ETM knows what a sensible input ratio is when this ratio isn't determined dynamically. Since merit is off in the start year, the shares for gas and electricity going to hybrid heatpumps are calculated in ETDataset in such way that they exactly match the input ratio. However, this doesn't merely seems to be a nicety, but an actual condition/requirement for the graph to be initialised:
these input slots turn up in the sparse graph and manually removing them still results in the same Refinery error.

**Comment by DorinevanderVlies** [comment]
> However, it does seem that NL is the only dataset with non-zero demand for HHPs.

That's correct as far as I am aware. It required quite  elaborate calculations for that dataset to get the gas and electricity ratio going to HHP's correct and get refinery to initialize the graph

**Comment by antw** [comment]
> I've created a dummy local dataset to test the initializer methods. When setting:
`households_final_demand_electricity: demand: 1000.0` (or network_gas so you like), Refinery fails:

This failure seems reasonable to me. The initializer method increases (for the sake of this example) the amount of electricity available, but does not change the share of any of the outputs of the "electricity final demand" or "space heating electricity final demand" nodes. This means that each output (appliances, heating, cooling, etc) receives an increase in electricity supply.

But why should that be the case? Is there an increase in space heating demand? Does the HHP in this dataset consume more electricity and ambient heat – and less gas – than in the standard NL dataset? How is that extra electricity used?

The amount of electricity in this dataset has changed, but the *consequences* of that change must also be specified.

> It required quite elaborate calculations for that dataset to get the gas and electricity ratio going to HHP's correct and get refinery to initialize the graph

I think this also implies that other datasets *cannot* have HHPs present unless their final demands for electricity and network gas have exactly the same proportions as in the NL dataset?

**Comment by michieldenhaan** [comment]
> I think this also implies that other datasets cannot have HHPs present unless their final demands for electricity and network gas have exactly the same proportions as in the NL dataset?

Yes indeed.

If I set other carrier demands like ``households_final_demand_coal: 1000.0`` or if I set the electricity and gas going to hybrid heat pumps to 0, everything works fine and I can change more or less any demand, application share and tech share I want. These changes indeed result in increased space heating demand, LED lighting demand, dishwasher demand etc., but that's precisely what we want: tailor a dataset in such a way that it resembles the local area we are interested in as closely as possible. It is just when these changes affect the energy going into a hybrid heat pump that the whole thing breaks down, because electricity and gas inputs have to match the input ratio up to 7 decimal places.

For ETLocal, I don't think it's feasible to take these extra conditions/interdependencies into account, because that more or less comes down to making a Ruby version of ETDataset to make sure the (input) shares are aligned. As I said, ideally we would be able to initialize the graph by independently setting any sparse graph demand and shares we want. This may indeed mean that for local datasets, the input ratio of gas and electricity for hybrid heatpumps in the starting year is a little off, but this is a small price to pay I would say.

I suspect that there are quite a few more of these cases in which simply setting random shares and demands break Refinery, @grdw and I are investigating that now.

**Comment by grdw** [comment]
Following @michieldenhaan very own tip. You are able to tweak the input shares for HHP's. 

So:

```yaml
---
households_final_demand_network_gas:
  demand: 1000.0

households_space_heater_hybrid_heatpump_air_water_electricity:
  input:
    network_gas: 0.00275
    electricity: 0.99725
    ambient_heat: 0.0

households_water_heater_hybrid_heatpump_air_water_electricity:
  input:
    network_gas: 0.9
    electricity: 0.1
    ambient_heat: 0.0
```

The tweaking itself is rather cumbersome though 😞 to make it exactly matchy matchy something else.

**Comment by antw** [comment]
> do you know if this input ratio requirement can be removed/softened. I.e. that Refinery simply continues calculating even though the ratio of electricity and gas coming into the hybrid heat pump is not exactly as specified in the .ad file?

Currently no. Any information provided to Refinery is treated as fact, not suggestion. If it is told that the shares for HHPs are *x* and *y*, it assumes that you know this is true.

However, even if Refinery could treat these values more loosely, it wouldn't work: removing the shares from `graph.yml` (thus making it Refinery's responsibility to figure out what they are) results in an incalculable graph; there's no longer enough information to compute the dataset.

My first instinct is that this is another good argument for splitting the HHP into two separate components (one for electricity, one for gas) but it's possible that this just shifts the problem to a different node/edge. It would also impact Merit and dynamic-heat, so it's not remotely realistic to do this on the timescale permitted by the fact-sheet project.

It does seem wrong that the HHP input shares are so dependant on final demand for electricity and gas; I will investigate further.

**Comment by ChaelKruip** [comment]
> However, even if Refinery could treat these values more loosely, it wouldn't work: removing the shares from graph.yml (thus making it Refinery's responsibility to figure out what they are) results in an incalculable graph; there's no longer enough information to compute the dataset.

As I understand it, the only thing that Refinery cares about is having enough information to take the next step in evaluating the energy-flow in the graph. The current choice of setting the inputs of the HHP is just one of the possibilities right @antw? I can imagine that we allow the input ratio of the HHP to be defined by Refinery but have to set other shares etc. in order to make it calculable.

**Comment by michieldenhaan** [comment]
> However, even if Refinery could treat these values more loosely, it wouldn't work: removing the shares from graph.yml (thus making it Refinery's responsibility to figure out what they are) results in an incalculable graph; there's no longer enough information to compute the dataset.

It looks like ambient heat is the culprit here. If you remove both electricity and gas inputs from the sparse graph, Refinery probably doesn't have enough information to calculate the amount of ambient heat going into the heatpump. I tried to remove only input.network_gas (or input.electricity for that matter) from the sparse graph, and now I'm able to set non-zero shares of gas and electricity going to heat pumps! Have to test this a little bit more, but this essentially removes the coupling between gas and electricity in the sparse graph.

**Comment by michieldenhaan** [comment]
Passed the ``rspec spec/calculate_spec.rb`` (so no energy mismatch anymore!), but a regular ``rspec`` now returns:
![snapshot](https://user-images.githubusercontent.com/32056448/35226638-33aab45c-ff8c-11e7-9bc3-9bafc2f4c406.png)

**Comment by michieldenhaan** [comment]
Unfortunately removing the ``input.network_gas`` attribute from the HHP nodes also requires conflating the ``output.useable_heat.ambient_heat``, ``output.useable_heat.electricity`` and ``output.useable_heat.network_gas`` attributes into one single ``output.useable_heat`` attribute (to get rid of the error in my previous post). Currently, 1 MJ of ambient/electricity/gas input leads to respectively 1, 1 and 0.9 MJ of useable_heat output for hot water and 1, 1 and 1.067 MJ of useable_heat output for space heating. When removing these attributes and adding one single ``output.useable_heat = 1`` space heating heat pumps work fine, but hot water heat pumps now consume 100% gas (no electricty nor ambient heat) when merit is on.

Discussed this with @antw and we propose to leave this issue for now by setting HHP shares to 0 in local datasets. For the long term, we can either try to think of a way to redesign HHPs or add some transformation machinery to ETLocal that suits Refinery's needs (this would probably come down to overwriting the input attributes, as calculating the correct parent_shares is even more cumbersome).

**Comment by michieldenhaan** [comment]
We decided to tweak the input slot shares based on the specified user demands (like
https://github.com/quintel/etlocal/issues/70#issuecomment-357646098). That means that the input shares for HHPs in local datasets follow from the choices the users makes regarding households final demand for gas and electricity, final demand share of gas/electricity going to space heating/hot water and technology shares. See https://github.com/quintel/etsource/pull/1696/commits/ff605f46accae5985f2ea5bfb22b63ddb87ba9ea

The main downside of this solution is that, depending on the user's choices, this may result in an unrealistic gas/electricity/ambient ratio for HHPs in the present year (and future year when merit is off). However, since the share of HHPs in the present is very low this seems reasonable (given that other potential solutions are either time consuming or limit the user in customizing datasets).
