### ISSUE TITLE
Transport sparse graph: mixers require input shares

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#71]
The sparse graph contains input shares for ``transport_road_mixer_lng``, ``transport_shipping_mixer_lng`` and ``transport_shipping_mixer_diesel``. As a result, to initialize the graph these input shares have to be overwritten to match the actual ratio of lng/bio_lng/diesel/biodiesel/heavy_fuel_oil coming into the mixers.
This requires (in my opinion unnecessary) calculations. It would be much easier if we can simply set parent_shares for different carriers. I.e.: how much of transport_final_demand_for_shipping_bio_lng goes to the lng_mixer and how much to the diesel mixer? If we do that for all the fuels in the mixer, Refinery should have sufficient information to initialize the graph.

![mix](https://user-images.githubusercontent.com/32056448/35038171-43dc620a-fb7a-11e7-9458-a77a6ec9683b.png)

Note that for other transport mixers (e.g. road_mixer_diesel or road_mixer_gasoline) the above problem does not occur because the sparse graph already contains shares rather than inputs.

Workaround: In the NL2015 dataset, each mixer has only one fuel coming in with a positive amount of energy (i.e. one fuel has input share 1, all other fuels have input share 0). As long as the final demands for these latter fuels are 0 as well, everything is fine.
Issue related to: https://github.com/quintel/etlocal/issues/70

**Comment by ChaelKruip** [comment]
@michieldenhaan can you make this ticket "actionable" and assign someone please?

**Comment by michieldenhaan** [comment]
Whitelisted all transport mixers with more than one carrier input and added sparse graph queries to set correct input shares, see https://github.com/quintel/etsource/pull/1702
In case that all input carriers are zero the default NL input shares are taken
