### ISSUE TITLE
Can't set steel sector to 0

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#73]
I'm trying to turn the steel sector off for local datasets, but I'm not able to get rid of some coal gas in the steel sector. As soon as I set:
``industry_final_demand_for_metal_electricity-industry_steel_blastfurnace_current_consumption_useable_heat@electricity:
  parent_share: 0.0``, I get a ``stack level too deep`` error. The reason for this (I think) is that there is some coal gas going into ``industry_steel_blastfurnace_burner_coal_gas``, where it is turned into heat and passed on to ``industry_steel_blastfurnace_current_consumption_useable_heat``. This blastfurnace requires some electricity to operate, so as soon as I set the electricity share for this node to 0.0, the coal gas heat is trapped, resulting in a stack level error.

The curious thing is that I can set ``industry_final_demand_for_metal_electricity-industry_steel_blastfurnace_current_consumption_useable_heat@electricity:
  parent_share`` to any value I want, as long as it is non-zero. The amount of coal gas in the system goes up or down with the amount of electricity.

@ChaelKruip and I tried to trace the source of this coal gas, but to no avail. Do you have any clue what is going on @antw? There is a (sort of) MWE on the etsource ``testing_init_methods`` branch.

**Comment by antw** [comment]
The node triggering this error is [industry_steel_blastfurnace_burner_coal_gas](https://beta-engine.energytransitionmodel.com/data/799495/converters/industry_steel_blastfurnace_burner_coal_gas).

In a normal graph where there is energy flow to this node, Refinery is able to look at the amount of coal, coal_gas, and network_gas, and determine the input share of the three carriers. For example, 0PJ coal, 70PJ coal_gas, and 30PJ network_gas obviously results in shares of 0, 0.7, and 0.3 respectively.

However, if the demands of the three carriers is 0PJ, 0PJ, and 0PJ, there's no way for Refinery to figure out what the shares are.

I can fix the "SystemStackError: stack level too deep" to provide a more meaningful message, but the problem will remain that Refinery has insufficient information to calculate the shares:

```
Post-calculation validations failed with the following errors:

  * #<Refinery::Slot (in, coal) node=:industry_steel_blastfurnace_burner_coal_gas> has an undetermined share
  * #<Refinery::Slot (in, coal_gas) node=:industry_steel_blastfurnace_burner_coal_gas> has an undetermined share
  * #<Refinery::Slot (in, network_gas) node=:industry_steel_blastfurnace_burner_coal_gas> has an undetermined share
```

**Comment by antw** [comment]
FYI If you're looking to turn off the *whole* metal sector, instead of just steel, you can set `- has_metal = false` in the dataset file.

**Comment by michieldenhaan** [comment]
Is there a reason why this happens particularly to the ``industry_steel_blastfurnace_burner_coal_gas`` node? There are plenty of other nodes that have multiple carrier inputs which can safely be set to 0. Most local regions will have some 'other metals' industry but no steel/aluminium, so ``- has_metal = false`` is typically not an option.

**Comment by antw** [comment]
> There are plenty of other nodes that have multiple carrier inputs which can safely be set to 0.

I expect those that allow the inputs to be set to zero specify the shares manually in the node document, and are based on researched/known input efficiencies. For example [industry_steel_blastfurnace_current_consumption_useable_heat](https://github.com/quintel/etsource/blob/8bbbdaf7b02fd01a865e6a058556739ba5c352c2/nodes/industry/industry_steel_blastfurnace_current_consumption_useable_heat.converter.ad#L3-L4) (in quintel/etsource@22ee7c5):

```
- input.electricity = 0.22021688790469
- input.useable_heat = 0.77978311209531
```

**Comment by michieldenhaan** [comment]
Hm, so can you think of any way to set all steel sector demands to 0? How does the ``has_metal = false`` statement achieve that?

**Comment by antw** [comment]
> How does the has_metal = false statement achieve that?

It sets *everything* – throughout the entire sector – to zero. All the demands and all the shares are set to zero. As the relevant sliders are hidden in the ETM, that works just fine.

However, if the metal sector is to remain enabled then it will be possible for a user to add steel furnaces, and cause energy to flow into those nodes. ETEngine *must* therefore know the share of those inputs (electricity and useable heat).

The only solution I know of is to explicitly set the shares, either in the document itself or by whitelisting the node and setting something in graph_values.yml.

**I wonder if it is a mistake that the coal_gas file doesn't have any `input` values**; many other "current_consumption" converters do:

* [industry_steel_blastfurnace_current_consumption_useable_heat](https://github.com/quintel/etsource/blob/master/nodes/industry/industry_steel_blastfurnace_current_consumption_useable_heat.converter.ad)
* [industry_steel_blastfurnace_current_consumption_useable_heat](https://github.com/quintel/etsource/blob/master/nodes/industry/industry_steel_blastfurnace_current_consumption_useable_heat.converter.ad)
* [industry_steel_hisarna_consumption_useable_heat](https://github.com/quintel/etsource/blob/master/nodes/industry/industry_steel_hisarna_consumption_useable_heat.converter.ad)
* etc...

**Comment by michieldenhaan** [comment]
Thanks! For now I've set the electricity share for ``industry_steel_blastfurnace_current_consumption_useable_heat`` to some very small number, resulting in a nice and colourful 0 joule steel sector:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://user-images.githubusercontent.com/32056448/35681921-49a95454-075f-11e8-8483-979db6d67370.png)

I'll try to find a more permanent solution later on.

**Comment by michieldenhaan** [comment]
Aaand it's gone:
![energy transition model - your free independent comprehensive fact-based scenario builder httpetmodel test 2018-03-02 09-28-29](https://user-images.githubusercontent.com/32056448/36889905-3a8f56ae-1dfc-11e8-83b1-4c47f9a958ca.png)

Whitelisted input shares for ``industry_steel_blastfurnace_burner_coal_gas`` and added:

![graph_values yml projectsetsourcedatasetsrivierenland 2018-03-02 09-28-56](https://user-images.githubusercontent.com/32056448/36889911-3d6d7ad6-1dfc-11e8-9743-5be2ace934f4.png)

to graph_values.yml.

Thanks @antw!

**Comment by michieldenhaan** [comment]
Same issue occurs with ``industry_other_metals_burner_network_gas`` when it receives no energy (i.e. when steel, aluminium AND other metals ``coal``, ``crude oil`` and ``network gas`` are all zero).
Temporarily circumvented by whitelisting input shares (https://github.com/quintel/etsource/commit/556d3512b086872cc2dd303bf2a1f2f1167c6247) but a more permanent solution is desirable.

**Comment by grdw** [comment]
Maybe we can rename this issue to: when all the demands of a certain set of nodes are zero, the corresponding input ratio should be determined - or guessed by Refinery.
