### ISSUE TITLE
Percentages in front-end should be a value between 0 and 1

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#79]
Currently it's a value between 0 and 100.

**Comment by grdw** [comment]
@antw how would you approach this issue. Would this be as simple as setting the min and max to 0 and 1 in the front-end for the [Quinn slider](https://github.com/antw/quinn#minima-and-maxima-min-value-max-value-extrema) (and make it look like 1 and 100 in the front-end?). Or would this be a step that needs to be done further down the line (when saving to the database?).

**Comment by antw** [comment]
> @antw how would you approach this issue.

I think it comes down to individual choice, and I'm not sure there's a correct answer. Inputs used by ETModel are percentages (0-100) [which then divide the input value by 100](https://github.com/quintel/etsource/blob/f9cfef6fc0d7dc205245d77f3ebbc0e99cf07a9f/inputs/demand/households/households_hot_water/households_water_heater_hybrid_heatpump_air_water_electricity_share.ad#L1-L5).

It also seems perfectly valid to have the input be a value between 0 and 1 and format the value as a percentage in the UI.

**Comment by ChaelKruip** [comment]
> It also seems perfectly valid to have the input be a value between 0 and 1 and format the value as a percentage in the UI.

I like that.
