### ISSUE TITLE
Make it possible to add single sliders alongside slider groups

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etlocal#90]
![image](https://user-images.githubusercontent.com/1303760/39528539-a4382f2e-4e24-11e8-9776-3a3440a74e82.png)

This could be solved by making `Input households solar pv own use share` a slider

**Comment by grdw** [comment]
Or do you mean 0 - 1? :thinking:

**Comment by ChaelKruip** [comment]
The frontend can use 0 - 100% if that is doable. The query should use 0 - 1. 

If it is a pain to make the frontend display 0 - 100 (while communicating 0 - 1 to the backend, I suppose I could live with sliders showing 0 - 1 in the frontend as well for the MVP. This is cosmetics in the end.

**Comment by grdw** [comment]
It's doing exactly that. The value is between 0 and 1. But the slider shows a value between 0 and 100. 

The moment it sets the value to an `<input>` (read: HTML-input) - it divides it by a 100.

**Comment by ChaelKruip** [comment]
> It's doing exactly that.

My point is that this particular input is not yet a 'slider' and currently allows the user to set values larger than 100. This should not be possible.

**Comment by michieldenhaan** [comment]
This has been enabled a while ago, see https://github.com/quintel/etlocal/commit/495f76e48d595a51ad22d4aa0272f903953e3918
