### ISSUE TITLE
Add hidden area attribute called 'group' 

### ISSUE THREAD

**Issue by grdw** [quintel/etlocal#92]
Automatically set the [group](https://github.com/quintel/etlocal/blob/master/app/models/dataset.rb#L12-L22) of the dataset.

**Comment by michieldenhaan** [comment]
Feedback from meeting yesterday: would be nice if the area classification would show up in the ETLocal front-end, e.g.: Lutjebroek (buurt)

**Comment by grdw** [comment]
I've added it to the pop-up:

![screen shot 2018-05-22 at 15 25 23](https://user-images.githubusercontent.com/2676542/40365244-5fb22958-5dd4-11e8-9004-f99d5c3bbece.png)

so you know at which 'level' you are in the areas.

**Comment by michieldenhaan** [comment]
Nice! does this also set the group attribute in the area file of the dataset?
