### ISSUE TITLE
Post calculation validation - rounding errors?

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etlocal#95]
I get the following post calculation validation errors (see below). Since the numbers are so close, I suspect that the numbers get rounded somewhere?
![monosnap 2018-05-07 16-31-50](https://user-images.githubusercontent.com/32056448/39707256-2f5d0712-5214-11e8-989c-0a6d9fdb00e3.png)

BTW: Refinery reports PJ while in fact these values are TJ, so the mismatch should be divided by 1000

**Comment by grdw** [comment]
I don't think the numbers are rounded somewhere.... I think this might actually be the limitation to a Float:

```
* #<Refinery::Slot (out, network_gas) node=:buildings_final_demand_network_gas> demand (21,897.791241 PJ) does not match output of the node (21,897.8 PJ) (-8,759,120 MJ) 
* #<Refinery::Slot (out, network_gas) node=:households_final_demand_for_space_heating_network_gas> demand (38,899.014099 PJ) does not match output of the node (38,899.028297 PJ) (-14,198,145.328332 MJ) 
* #<Refinery::Slot (out, network_gas) node=:households_final_demand_network_gas> demand (49,413.585176 PJ) does not match output of the node (49,413.6 PJ) (-14,824,080 MJ) 
* #<Refinery::Slot (out, useable_heat) node=:households_water_heater_solar_thermal> demand (157.633059 PJ) does not match output of the node (157.633 PJ) (+0.059455 TJ) 
* #<Refinery::Slot (out, compressed_network_gas) node=:transport_road_mixer_compressed_network_gas> demand (214.429983 PJ) does not match output of the node (214.43 PJ) (-16,692.067263 MJ) 
* #<Refinery::Slot (out, gasoline_mix) node=:transport_road_mixer_gasoline> demand (39.999983 PJ) does not match output of the node (40 PJ) (-16,760.696908 MJ) 
* #<Refinery::Slot (in, bio_lng) node=:transport_road_mixer_lng> demand (20 PJ) does not match demand from the node (49.6403 PJ) (-29,640,300,000 MJ)
```

The `transport_road_mixer_gasoline` is incorrect not due to the rounding.. when changing the numbers something else goes wrong.

**Comment by grdw** [comment]
I fixed it in the front-end items. It's a bit tricky to get rid off, but what you do locally is:

- Run the migrations (with `rake db:migrate`)
- Copy the defaults csv from the Dropbox (or from the link on Slack)
- Put in the `db/datasets` folder.
- Run `rake db:seed`. 
- 🎊 fixed

There's one Refinery error left:

<img width="953" alt="screen shot 2018-05-08 at 09 57 16" src="https://user-images.githubusercontent.com/2676542/39744980-3b976be8-52a6-11e8-83ef-124e6d2d32a6.png">
